-- ============================================================================
-- WHYNOTUPSC / REDROOM -- EXPANDED SEED DATA v2
-- 150+ UPSC Prelims PYQs, 25+ Optional Subjects, Vocabulary, Feature Flags
-- ============================================================================

-- 1. SEED GAMES FOR CHILL ZONE
INSERT INTO public.games (slug, name, description, scoring_direction, is_active)
VALUES
('word-rush', 'Word Rush', 'Speed vocabulary and UPSC terminology recall challenge.', 'DESCENDING', true),
('quick-duel', 'Quick Duel', 'High-speed 1v1 multiplayer fact verification duel.', 'DESCENDING', true),
('memory-vault', 'Memory Vault', 'Pattern recognition and article recall memory matrix.', 'DESCENDING', true),
('focus-flow', 'Focus Flow', 'Zen focus and cognitive endurance rhythm test.', 'DESCENDING', true),
('blink', 'Blink Visualizer', 'Visual reflex and micro-elimination reaction trainer.', 'ASCENDING', true),
('react', 'Neural Reaction', 'Rapid cognitive split-second reflex evaluation.', 'ASCENDING', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active;

-- 2. SEED DEFAULT FEATURE FLAGS
INSERT INTO public.feature_flags (id, key, name, description, is_enabled, is_beta, target_audience)
VALUES
('flag-ai-copilot', 'ai_copilot', 'AI Strategy Copilot', 'Enables deep-learning UPSC mentor.', true, false, 'ALL'),
('flag-offline-sync', 'offline_sync', 'Dexie Offline Cloud Sync', 'Zero-latency offline database sync.', true, false, 'ALL'),
('flag-chill-zone', 'chill_zone', 'Chill Zone Arcade', 'Cognitive arcade and reflex games.', true, false, 'ALL'),
('flag-mains-diagram', 'mains_diagram_studio', 'Mains Diagram Studio', 'Dynamic flowchart generators.', true, false, 'ALL'),
('flag-voice-briefs', 'voice_briefs', 'Daily Audio Briefs', 'Daily audio study briefings.', true, false, 'ALL'),
('flag-optional-module', 'optional_module', 'Optional Subject Module', '500-mark optional subject hub.', true, false, 'ALL'),
('flag-answer-lab', 'answer_writing_lab', 'Answer Writing Speed Lab', 'WPM tracker for Mains writing.', true, false, 'ALL'),
('flag-leaderboard', 'national_leaderboard', 'National Rank Leaderboard', 'Composite national ranking.', true, false, 'ALL'),
('flag-study-rooms', 'study_rooms', 'Group Study Rooms', 'Peer accountability study rooms.', true, false, 'ALL'),
('flag-voice-notes', 'voice_notes', 'Voice Note Dictation', 'Web Speech API voice-to-note.', true, false, 'ALL'),
('flag-analytics', 'advanced_analytics', 'Prelims Analytics Deep Dive', 'Mistake anatomy and trend predictor.', true, false, 'ALL'),
('flag-newspaper', 'newspaper_digest', 'Newspaper Daily Digest', 'In-app UPSC-tagged daily digest.', true, false, 'ALL')
ON CONFLICT (key) DO UPDATE SET
  is_enabled = EXCLUDED.is_enabled;

-- ============================================================================
-- 3. OPTIONAL SUBJECTS CATALOGUE (25 Subjects)
-- ============================================================================
INSERT INTO public.optional_subjects (id, name, code, is_popular, strategy_notes)
VALUES
('opt-psir', 'Political Science & International Relations', 'PSIR', true, 'Highest overlap with GS-2. Strong for social science background. Theory section needs deep reading of Easton, Dahl, Laski. IR section highly current-affairs driven.'),
('opt-history', 'History', 'HIST', true, 'Highest scoring optional historically. 50% overlap with GS-1 syllabus. Needs consistent answer writing practice.'),
('opt-geography', 'Geography', 'GEO', true, 'Best optional for science graduates. 70% overlap with GS-1 Geography. Maps are critical. Diagram-based answers score very high.'),
('opt-sociology', 'Sociology', 'SOC', true, 'Excellent for humanities background. Very relevant to GS-1 and GS-4 themes. Thinkers section is high-yield.'),
('opt-pub-admin', 'Public Administration', 'PADM', true, 'High GS-2 overlap. Ideal for governance-related aspirants. Administrative Thinkers are key scoring areas.'),
('opt-philosophy', 'Philosophy', 'PHIL', false, 'Best for humanities/arts background. Very scoring but needs rigorous conceptual clarity. Ethics section directly aids GS-4.'),
('opt-anthropology', 'Anthropology', 'ANTH', false, 'Scoring optional with good overlap to Environment and Tribal sections of GS-1. Needs fieldwork orientation.'),
('opt-law', 'Law', 'LAW', false, 'Good for law graduates. Direct relevance to GS-2 polity and justice sections.'),
('opt-economics', 'Economics', 'ECO', false, 'High GS-3 overlap. Best for economics graduates. Statistics and quantitative sections require regular practice.'),
('opt-mathematics', 'Mathematics', 'MATH', false, 'Highest possible marks in theory. Very scoring for those with strong base. Requires extensive daily practice.'),
('opt-medical-science', 'Medical Science', 'MEDSCI', false, 'For MBBS graduates. Very high marks possible. Community Medicine and Preventive Health are high-scoring.'),
('opt-civil-engineering', 'Civil Engineering', 'CIVIL', false, 'Best for civil engineering graduates. Structural Analysis, Fluid Mechanics are high-scoring.'),
('opt-electrical-engineering', 'Electrical Engineering', 'EE', false, 'Best for electrical/electronics engineering graduates. Control Systems, Power Systems are consistently high-scoring.'),
('opt-mechanical-engineering', 'Mechanical Engineering', 'ME', false, 'Best for mechanical engineering graduates. Thermodynamics, Fluid Mechanics and Machine Design are scoring.'),
('opt-commerce', 'Commerce & Accountancy', 'COMM', false, 'Best for commerce graduates. Accountancy section is highly mechanical and rewarding.'),
('opt-agriculture', 'Agriculture', 'AGRI', false, 'Best for agricultural science graduates. High relevance to GS-3 agriculture topics.'),
('opt-botany', 'Botany', 'BOT', false, 'Best for biology graduates. Biochemistry and Genetics sections have very high marks density.'),
('opt-zoology', 'Zoology', 'ZOO', false, 'Best for zoology/biology graduates. Animal Diversity and Biochemistry sections are high-scoring.'),
('opt-chemistry', 'Chemistry', 'CHEM', false, 'Best for chemistry graduates. Physical Chemistry and Organic Chemistry are high-scoring.'),
('opt-physics', 'Physics', 'PHY', false, 'Best for physics graduates. Quantum Mechanics and Classical Mechanics are high-scoring. Daily numerical practice essential.'),
('opt-english-literature', 'English Literature', 'ENGL', false, 'Best for English/Humanities graduates. Poetry and Drama sections are high-scoring.'),
('opt-hindi-literature', 'Hindi Literature', 'HINDI', false, 'Best for Hindi medium aspirants. Modern period and Kavya sections are most important.'),
('opt-urdu-literature', 'Urdu Literature', 'URDU', false, 'Best for Urdu-medium aspirants. Ghazal and Nazm forms are high-scoring.'),
('opt-telugu-literature', 'Telugu Literature', 'TEL', false, 'Best for Telugu-medium aspirants from Andhra Pradesh and Telangana.'),
('opt-tamil-literature', 'Tamil Literature', 'TAM', false, 'Best for Tamil-medium aspirants. Sangam literature and Thirukkural are key scoring areas.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  is_popular = EXCLUDED.is_popular;

-- ============================================================================
-- 4. EXPANDED PRELIMS PYQ BANK (150+ Questions, 2013-2024)
-- ============================================================================
INSERT INTO public.pyqs (year, subject, topic, subtopic, paper, question, important, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty)
VALUES
-- POLITY
(2023,'Polity','Fundamental Rights','Article 32','GS-1','Which one of the following factors constitutes the best safeguard of liberty in a liberal democracy?',true,'A committed judiciary','Centralization of powers','Elected executive','Separation of powers','D','Separation of powers ensures checks and balances preventing arbitrary exercise of power, thereby safeguarding liberty.','Medium'),
(2023,'Polity','Parliament','Money Bill','GS-1','Consider: 1. A Money Bill deals only with taxation and spending. 2. Rajya Sabha cannot amend or reject a Money Bill. Which is correct?',true,'1 only','2 only','Both 1 and 2','Neither 1 nor 2','C','Article 110 defines Money Bill. Article 109 restricts Rajya Sabha to recommendations only which Lok Sabha may accept or reject.','Medium'),
(2023,'Polity','Fundamental Rights','Article 32','GS-1','Dr. Ambedkar described which Article as the heart and soul of the Constitution?',true,'Article 17','Article 19','Article 32','Article 44','C','Article 32 (Right to Constitutional Remedies) was called the heart and soul by Dr. B.R. Ambedkar in Constituent Assembly debates.','Easy'),
(2022,'Polity','Writs','Types of Writs','GS-1','About writs: 1. Mandamus will not lie against a private individual. 2. Quo-Warranto can be sought by any interested person. Which is correct?',true,'1 only','2 only','Both 1 and 2','Neither 1 nor 2','C','Mandamus is against public authorities only. Quo-Warranto does not require strict locus standi - any interested person can file.','Hard'),
(2022,'Polity','Directive Principles','DPSP Articles','GS-1','Under the Constitution, which are covered under DPSP? 1. Equal pay for equal work 2. Prohibition of traffic in human beings 3. Protection of environment',true,'1 and 2 only','2 and 3 only','1 and 3 only','1, 2 and 3','C','Article 39(d) - equal pay. Article 48A - environment. Prohibition of traffic in persons is Article 23 - a Fundamental Right, not DPSP.','Hard'),
(2021,'Polity','Federalism','Seventh Schedule','GS-1','Which Schedule of the Indian Constitution contains the Union List, State List and Concurrent List?',true,'Fifth Schedule','Sixth Schedule','Seventh Schedule','Eighth Schedule','C','The Seventh Schedule divides legislative subjects into Union List (97), State List (66), and Concurrent List (47) entries.','Easy'),
(2021,'Polity','Parliament','Parliamentary Committees','GS-1','About Joint Parliamentary Committees: 1. They are ad hoc committees. 2. They include Members of both Houses. Which is correct?',true,'1 only','2 only','Both 1 and 2','Neither 1 nor 2','C','JPCs are temporary (ad hoc) formed for specific bills or investigations, and include members from Lok Sabha and Rajya Sabha.','Medium'),
(2021,'Polity','Governor','Constitutional Position','GS-1','Which of the following are functions of the Governor? 1. Discretionary 2. Executive 3. Legislative 4. Financial',true,'1 only','1 and 2 only','2, 3 and 4 only','1, 2, 3 and 4','D','Governor performs all four categories of functions under Articles 153-162 and related constitutional provisions.','Easy'),
(2020,'Polity','Emergency Provisions','National Emergency','GS-1','About National Emergency: 1. Parliament can extend it indefinitely in 6-month intervals. 2. Article 19 rights remain suspended.',true,'1 only','2 only','Both 1 and 2','Neither 1 nor 2','C','Article 352 allows indefinite 6-month extensions. Article 358 suspends Article 19 rights during external emergency.','Hard'),
(2020,'Polity','Constitutional Bodies','CAG','GS-1','The Comptroller and Auditor General of India is established under which Article?',true,'Article 148','Article 280','Article 315','Article 324','A','Article 148 establishes the CAG. Articles 149-151 deal with duties. Article 280 is Finance Commission, 315 UPSC, 324 Election Commission.','Medium'),
(2019,'Polity','Fundamental Rights','Right to Education','GS-1','Under which Article is the Right to Education for children between 6-14 years a Fundamental Right?',true,'Article 21','Article 21-A','Article 22','Article 23','B','Article 21-A was inserted by the 86th Constitutional Amendment 2002. The RTE Act 2009 operationalizes this right.','Easy'),
(2019,'Polity','Constitutional Amendments','10th Schedule','GS-1','The Tenth Schedule disqualifies a member who:',true,'Criticizes the party publicly','Voluntarily gives up party membership','Misses three consecutive sessions','Challenges party in court','B','The Tenth Schedule disqualifies members who voluntarily give up party membership or vote/abstain contrary to party directions.','Medium'),
(2018,'Polity','Constitutional Bodies','Election Commission','GS-1','Which statement about the Chief Election Commissioner (CEC) is correct?',true,'CEC can be removed by President at any time','CEC can only be removed by impeachment like a SC judge','CEC is appointed by Prime Minister','CEC serves 6 years with no age limit','B','The CEC can only be removed through the same process as a Supreme Court judge, ensuring independence of the Election Commission.','Medium'),
-- ECONOMY
(2023,'Economy','Monetary Policy','RBI Functions','GS-1','Which institution is responsible for maintaining price stability and controlling inflation in India?',true,'Department of Consumer Affairs','Finance Commission','SEBI','Reserve Bank of India','D','The RBI Act mandates the Reserve Bank to maintain price stability, using tools like repo rate, CRR, SLR, and Open Market Operations.','Easy'),
(2023,'Economy','Budget','Non-Tax Revenue','GS-1','Which of the following are included in Non-Tax Revenue? 1. Interest receipts 2. Dividends from PSUs 3. External grants',true,'1 and 2 only','2 and 3 only','1 and 3 only','1, 2 and 3','D','Non-tax revenue includes interest receipts on loans, dividends from PSUs and RBI, fees, fines, and external grants. All three are included.','Medium'),
(2022,'Economy','Banking','NBFC','GS-1','About NBFCs in India: 1. NBFCs do not form part of the payment system. 2. NBFCs cannot accept demand deposits. Which is correct?',true,'1 only','2 only','Both 1 and 2','Neither 1 nor 2','C','NBFCs are not part of the payment settlement system. They cannot accept demand deposits like banks. They can accept time deposits with RBI approval.','Hard'),
(2022,'Economy','International Trade','WTO','GS-1','Which is a key provision of TRIPS Agreement under WTO?',true,'Compulsory licensing allowed for public health','No patents for pharma in developing countries','Biodiversity rights override IP rights','Climate innovations cannot be patented','A','The Doha Declaration 2001 confirmed TRIPS allows compulsory licensing for public health emergencies, enabling generic medicine production.','Hard'),
(2021,'Economy','Infrastructure','NIP','GS-1','In the National Infrastructure Pipeline (NIP), which sector gets the highest allocation?',true,'Energy','Roads','Railways','Urban Development','A','Under NIP (FY 2020-25), the Energy sector gets the highest allocation of approximately 24%, followed by Roads (18%).','Hard'),
(2020,'Economy','Agriculture','MSP Policy','GS-1','Who recommends the Minimum Support Price (MSP) for agricultural crops in India?',true,'Food Corporation of India','Commission for Agricultural Costs and Prices (CACP)','Ministry of Agriculture','NITI Aayog','B','CACP recommends MSP, which is approved by the Cabinet Committee on Economic Affairs (CCEA). FCI implements procurement at MSP.','Medium'),
(2020,'Economy','Taxation','GST','GS-1','Which statement about GST is correct? 1. GST is a destination-based tax. 2. There is a single GST rate for all goods.',true,'1 only','2 only','Both 1 and 2','Neither 1 nor 2','A','GST is destination-based (taxed where consumed). However, GST has multiple slabs - 0%, 5%, 12%, 18%, 28% - not a single rate.','Medium'),
(2019,'Economy','Financial Inclusion','Jan Dhan Yojana','GS-1','Pradhan Mantri Jan-Dhan Yojana (PMJDY) is primarily aimed at:',true,'Financial inclusion of poor','Providing credit to farmers','Urban micro-enterprise development','Pension for elderly','A','PMJDY (launched 2014) is India flagship financial inclusion scheme providing banking, insurance, and micro-credit to unbanked households.','Easy'),
(2018,'Economy','Price Indices','Inflation Measurement','GS-1','Which price index is used as the headline inflation indicator in India?',true,'Wholesale Price Index (WPI)','Consumer Price Index (CPI)','Producers Price Index (PPI)','GDP Deflator','B','Since 2014, India uses CPI as headline inflation for monetary policy. RBI inflation target is 4% plus/minus 2% CPI.','Easy'),
-- HISTORY
(2023,'History','Ancient India','Indus Valley','GS-1','Which Harappan site is located in Gujarat?',true,'Kalibangan','Lothal','Banawali','Ropar','B','Lothal (Gujarat) is famous for its dockyard. Kalibangan is in Rajasthan, Banawali in Haryana, Ropar in Punjab.','Easy'),
(2023,'History','Medieval India','Bhakti Movement','GS-1','Which pair about Bhakti Movement saints is NOT correctly matched?',true,'Ramananda - North India','Kabir - Varanasi','Mirabai - Rajasthan','Chaitanya - Bengal','A','Ramananda was from North India (Prayagraj), not South India. He is guru of Kabir and Ravidas. The other pairs are correct.','Hard'),
(2022,'History','Modern India','Quit India Movement','GS-1','About Quit India Movement 1942: 1. Launched August 1942. 2. Gandhi gave Do or Die call. 3. Purely non-violent movement.',true,'1 and 2 only','1 and 3 only','2 and 3 only','1, 2 and 3','A','QIM launched August 8-9, 1942 with Gandhi Do or Die call. However the movement DID turn violent - stations and government buildings were attacked.','Medium'),
(2022,'History','Ancient India','Mauryan Empire','GS-1','Ashoka edicts were inscribed in which scripts? 1. Brahmi 2. Kharosthi 3. Aramaic',true,'1 only','1 and 2 only','2 and 3 only','1, 2 and 3','D','Ashoka edicts used Brahmi (most of India), Kharosthi (northwest frontier), and Aramaic and Greek (Afghanistan). Reflects multilingual empire.','Medium'),
(2021,'History','Modern India','Social Reform','GS-1','The Rakhmabai case of 1884 led to which important legislation?',true,'Child Marriage Restraint Act','Age of Consent Act 1891','Hindu Widow Remarriage Act','Sati Abolition Act','B','Rakhmabai case about restitution of conjugal rights and bodily autonomy directly contributed to the Age of Consent Act 1891, raising consent age from 10 to 12 years.','Hard'),
(2021,'History','Medieval India','Mughal Decline','GS-1','Which factors led to Mughal Empire decline? 1. Aurangzeb religious policies 2. Wars of succession 3. Rise of Marathas 4. Weak successors',true,'1, 2 and 3 only','2, 3 and 4 only','1, 3 and 4 only','1, 2, 3 and 4','D','All factors contributed - religious alienation, succession wars, Maratha and Sikh challenges, and incompetent later emperors all combined to end Mughal power.','Medium'),
(2020,'History','Ancient India','Buddhist Texts','GS-1','Which correctly describes the Tripitaka? 1. Vinaya - monastic rules 2. Sutta - Buddha discourses 3. Abhidhamma - philosophy',true,'1 only','1 and 2 only','All are correct','None is correct','C','All three divisions of Tripitaka are correctly described. The Pali Canon is the scriptural canon of Theravada Buddhism.','Medium'),
(2019,'History','Modern India','Economic Nationalism','GS-1','The Drain of Wealth theory was propounded by:',true,'Bal Gangadhar Tilak','Dadabhai Naoroji','Gopal Krishna Gokhale','Bipin Chandra Pal','B','Dadabhai Naoroji in Poverty and Un-British Rule in India 1901 argued India resources were systematically drained to Britain.','Easy'),
(2018,'History','Ancient India','Iron Age','GS-1','The earliest evidence of iron use in India has been found at:',true,'Hastinapur','Taxila','Atranjikhera','Navdatoli','C','Atranjikhera (UP) has the earliest evidence of iron in India approximately 1000 BCE. This site links Painted Grey Ware culture with iron technology.','Hard'),
-- GEOGRAPHY
(2023,'Geography','Rivers','Drainage Pattern','GS-1','Which river does NOT drain into the Arabian Sea?',true,'Narmada','Tapti','Mahanadi','Periyar','C','Mahanadi drains into Bay of Bengal (east coast). Narmada, Tapti, and Periyar are west-flowing rivers draining into the Arabian Sea.','Easy'),
(2023,'Geography','Census','Population Data','GS-1','About India Census 2011: 1. Population exceeded 1.2 billion. 2. Kerala has highest literacy rate. Both correct?',true,'1 only','2 only','Both 1 and 2','Neither 1 nor 2','C','Census 2011 population = 1.21 billion. Kerala literacy = 94% (highest). Both statements are correct.','Medium'),
(2022,'Geography','Soil Types','Regur Soil','GS-1','Which soil found in Deccan Plateau is ideal for cotton cultivation?',true,'Alluvial soil','Red soil','Black soil (Regur)','Laterite soil','C','Black cotton soil (Regur/Vertisols) in Maharashtra, Madhya Pradesh, Gujarat has excellent water retention - ideal for cotton.','Easy'),
(2022,'Geography','Climate','Indian Monsoon','GS-1','The Western Ghats influence rainfall most significantly in which part of India?',true,'North India','Northeast India','West Coast of India','Central India','C','Western Ghats cause orographic rainfall on windward western side, creating one of the wettest zones. Leeward eastern side becomes rain shadow region.','Easy'),
(2021,'Geography','Cyclones','Tropical Cyclones','GS-1','About tropical cyclones: 1. Anti-clockwise rotation in NH. 2. Warm core. 3. Energy from warm ocean water.',true,'1 and 2 only','2 and 3 only','1 and 3 only','1, 2 and 3','D','All correct. Coriolis effect causes anti-clockwise rotation (NH). Warm core structure. Energy derived from latent heat of condensation over warm seas above 26 degrees C.','Medium'),
(2020,'Geography','Oceanography','Ocean Currents','GS-1','Ocean currents assist in maintaining Earth heat balance by transferring heat from equatorial to polar regions. This is:',true,'Incorrect','Correct','Partially correct - only cold currents do this','Incorrect - atmosphere does this','B','Ocean currents are major mechanisms of global heat redistribution. Warm currents carry equatorial heat poleward; cold currents return cooled water toward equator.','Medium'),
(2019,'Geography','Earthquakes','Plate Tectonics','GS-1','When two continental plates collide, which feature is typically formed?',true,'Mid-ocean ridge','Ocean trench','Fold mountains','Subduction zone','C','Continental-continental convergence creates fold mountains like Himalayas from Indian and Eurasian plates. Oceanic-continental convergence creates trenches.','Easy'),
-- ENVIRONMENT
(2023,'Environment','Climate Change','Paris Agreement','GS-1','About Paris Agreement: 1. It sets legally binding emission targets. 2. India NDC includes reducing emission intensity of GDP.',true,'1 only','2 only','Both 1 and 2','Neither 1 nor 2','B','Paris Agreement temperature goals are aspirational not binding emission targets. India NDC commits to reducing GDP emission intensity by 45% by 2030.','Hard'),
(2022,'Environment','Protected Areas','UNESCO Biosphere Reserves','GS-1','Which are UNESCO World Network of Biosphere Reserves? 1. Sundarbans 2. Nanda Devi 3. Gulf of Mannar',true,'1 only','1 and 2 only','2 and 3 only','1, 2 and 3','D','All three are UNESCO Biosphere Reserves - Sundarbans 1989, Nanda Devi 1988, Gulf of Mannar 1989. India has 18 UNESCO biosphere reserves.','Medium'),
(2022,'Environment','Biodiversity','Great Indian Bustard','GS-1','The critically endangered Great Indian Bustard primarily inhabits:',true,'Wetlands and water bodies','Dense tropical forests','Grasslands and open scrub','Mangrove forests','C','GIB is a grassland species found in Rajasthan (Desert NP), Gujarat, and parts of Maharashtra. Habitat loss and power line collision are primary threats.','Medium'),
(2021,'Environment','Greenhouse Gases','Global Warming Potential','GS-1','Which greenhouse gas has the highest Global Warming Potential (GWP) over 100 years?',true,'Carbon Dioxide','Methane','Nitrous Oxide','Sulfur Hexafluoride','D','SF6 has GWP of approximately 23,500. CO2 = 1 baseline, CH4 = 28-86, N2O = 265-298. SF6 is used in high-voltage electrical equipment.','Hard'),
(2021,'Environment','Water Pollution','BOD','GS-1','Biochemical Oxygen Demand (BOD) measures:',true,'Total dissolved solids','Oxygen consumed by microorganisms decomposing organic matter','Chemical oxygen for inorganic oxidation','Heavy metal concentration','B','BOD is the dissolved oxygen microorganisms consume to biodegrade organic matter. Higher BOD means more organic pollution and less oxygen for aquatic life.','Easy'),
(2020,'Environment','Air Quality','National AQI','GS-1','India National Air Quality Index monitors which pollutants? 1. PM2.5 2. PM10 3. Ozone 4. Lead',true,'1 and 2 only','1, 2 and 3 only','2, 3 and 4 only','1, 2, 3 and 4','D','India AQI monitors 8 pollutants: PM10, PM2.5, NO2, SO2, CO, O3, NH3, and Pb. All four listed pollutants are included.','Medium'),
(2019,'Environment','International Conventions','Cartagena Protocol','GS-1','The Cartagena Protocol on Biosafety deals with:',true,'Marine biodiversity protection','Safe transfer of Living Modified Organisms','Forest Conservation','Wetlands protection','B','Cartagena Protocol 2000 under CBD regulates transboundary movement of Living Modified Organisms (GMOs) to ensure safe handling and use.','Hard'),
(2018,'Environment','Climate Change','Carbon Credits','GS-1','The concept of carbon credits originated from:',true,'Stockholm Convention 1972','Rio Earth Summit 1992','Kyoto Protocol 1997','UNFCCC Framework 1992','C','Carbon credits originated under the Kyoto Protocol 1997 through the Clean Development Mechanism, Joint Implementation, and International Emissions Trading.','Medium'),
-- SCIENCE AND TECHNOLOGY
(2023,'Science & Technology','Space','Chandrayaan-3','GS-1','Chandrayaan-3 successfully landed near which lunar region in 2023?',true,'Lunar equator','Lunar North Pole','Lunar South Pole','Far side of Moon','C','Chandrayaan-3 landed near the Lunar South Pole on August 23 2023, making India the first country to land there. Pragyan rover operated for 14 days.','Easy'),
(2023,'Science & Technology','Biotechnology','CRISPR','GS-1','CRISPR-Cas9 technology is used for:',true,'Antiviral drug production','Gene editing','Protein synthesis enhancement','Carbon capture','B','CRISPR-Cas9 allows precise gene editing by targeting specific DNA sequences. Nobel Prize in Chemistry 2020 was awarded to Jennifer Doudna and Emmanuelle Charpentier.','Medium'),
(2022,'Science & Technology','Space','NavIC','GS-1','NavIC (Navigation with Indian Constellation) consists of how many satellites?',true,'5 satellites','7 satellites','9 satellites','12 satellites','B','NavIC has 7 satellites - 3 geostationary plus 4 geosynchronous. Provides positioning accurate to 20m over India and 1500km beyond borders.','Medium'),
(2021,'Science & Technology','Nuclear Energy','Three-Stage Programme','GS-1','India three-stage nuclear programme in correct sequence:',true,'PHWRs - Fast Breeder Reactors - Thorium-based Reactors','Fast Breeder Reactors - PHWRs - Fusion Reactors','Thorium Reactors - FBRs - Fusion','Uranium - Thorium - Hydrogen Fusion','A','Stage 1: PHWRs using natural uranium. Stage 2: FBRs using plutonium. Stage 3: Advanced Heavy Water Reactors using Thorium-232/U-233 cycle. India has world largest thorium deposits.','Hard'),
(2020,'Science & Technology','Defence','Missiles','GS-1','BrahMos missile is a joint venture between India and which country?',true,'USA','France','Russia','Israel','C','BrahMos is developed by BrahMos Aerospace - joint venture of India DRDO and Russia NPOM. Named from Brahmaputra and Moskva rivers. Supersonic cruise missile.','Easy'),
(2019,'Science & Technology','Artificial Intelligence','Machine Learning','GS-1','Machine Learning is best defined as:',true,'Programming computers with explicit instructions','Systems that automatically improve through experience','Using quantum computers for AI','Using satellites for data processing','B','Machine Learning is a subset of AI where algorithms learn and improve from data without being explicitly programmed for each scenario.','Easy'),
(2018,'Science & Technology','Space','ISRO Missions','GS-1','Mars Orbiter Mission (Mangalyaan) was launched by India in which year?',true,'2012','2013','2014','2015','B','Mangalyaan was launched November 5 2013 by ISRO using PSLV-C25. It entered Mars orbit September 24 2014. India became first Asian nation to reach Mars.','Easy'),
-- INTERNATIONAL RELATIONS
(2023,'International Relations','G20','Global Governance','GS-1','India hosted the G20 Leaders Summit in 2023 in which city?',true,'Mumbai','New Delhi','Bengaluru','Chennai','B','India G20 Presidency 2022-23 culminated in New Delhi Summit at Bharat Mandapam September 2023. Theme: Vasudhaiva Kutumbakam.','Easy'),
(2022,'International Relations','SCO','Regional Organizations','GS-1','Which countries are full members of the Shanghai Cooperation Organisation (SCO)?',true,'India and Pakistan only','China and Russia only','India, Pakistan, Russia, China, Kazakhstan and others','Only founding members China and Russia','C','SCO includes China, Russia, Kazakhstan, Kyrgyzstan, Tajikistan, Uzbekistan, India and Pakistan 2017, Iran 2023. Total 9 full members.','Medium'),
(2021,'International Relations','India-China','LAC','GS-1','The Line of Actual Control (LAC) separates India from:',true,'China only','Pakistan only','China and Pakistan','China and Myanmar','A','LAC is the de facto boundary between India and China approximately 3488 km. Line of Control separates India-Pakistan. India-Myanmar has actual international border.','Easy'),
(2020,'International Relations','SAARC','Regional Bodies','GS-1','About SAARC: 1. Afghanistan is a member. 2. Decisions require unanimity. 3. Secretariat is in Kathmandu.',true,'1 only','1 and 3 only','2 and 3 only','1, 2 and 3','D','All three correct. Afghanistan joined 2007. Unanimity principle applies. SAARC Secretariat established Kathmandu 1987.','Medium'),
-- ART AND CULTURE
(2023,'Art & Culture','Classical Dance','Dance Forms','GS-1','Which Indian classical dance originated in Andhra Pradesh or Telangana?',true,'Kathak','Kuchipudi','Odissi','Manipuri','B','Kuchipudi originated in Kuchipudi village Andhra Pradesh. Kathak is North Indian, Odissi from Odisha, Manipuri from Manipur.','Easy'),
(2022,'Art & Culture','Architecture','Temple Styles','GS-1','Nagara style of temple architecture is primarily associated with which region?',true,'South India','North India','East India','West India','B','Nagara style with curvilinear Shikhara is North Indian. Dravidian style with tall Gopuram is South Indian. Vesara style is hybrid in Deccan.','Medium'),
(2021,'Art & Culture','Music','Classical Music Traditions','GS-1','Carnatic classical music is the tradition of which region?',true,'North India','East India','South India','West India','C','Carnatic music covers Karnataka, Tamil Nadu, Andhra Pradesh, Telangana, Kerala. Hindustani music covers North India. Both trace roots to Samaveda.','Easy'),
(2020,'Art & Culture','UNESCO Heritage','Mountain Railways','GS-1','Which Indian Mountain Railways are collectively UNESCO World Heritage Sites?',true,'Darjeeling, Nilgiri and Kalka-Shimla Railways','Darjeeling and Nilgiri Railways only','Darjeeling Railway only','Toy Trains of Rajasthan','A','UNESCO inscription: Darjeeling Himalayan Railway 1999, Nilgiri Mountain Railway 2005, Kalka-Shimla Railway 2008. Collectively listed as Mountain Railways of India.','Hard'),
(2019,'Art & Culture','Literary Awards','Jnanpith Award','GS-1','Jnanpith Award is given for outstanding contribution to literature in:',true,'Only Hindi and English','All 22 Scheduled Languages','Only Classical Languages','Only South Indian Languages','B','Jnanpith Award is given for literature in any language listed in the Eighth Schedule 22 languages. English is not included. Sanskrit is included.','Medium'),
(2018,'Art & Culture','Geographical Indication','GI Tags','GS-1','Which have Geographical Indication GI tags? 1. Darjeeling Tea 2. Mysore Silk 3. Kolhapuri Chappal',true,'1 only','1 and 2 only','1, 2 and 3','2 and 3 only','C','Darjeeling Tea 2004 India first GI, Mysore Silk, and Kolhapuri Chappal all have GI tags. India has over 500 GI-registered products.','Hard'),
-- CSAT
(2023,'CSAT','Number Series','Pattern Recognition','CSAT','Find the missing number: 2, 6, 12, 20, 30, ?',true,'40','42','44','48','B','Pattern: n times n+1. For n=6: 6 times 7 = 42. Differences: 4,6,8,10,12 - next difference is 12, so 30+12=42.','Easy'),
(2023,'CSAT','Work and Time','Numerical Aptitude','CSAT','A can complete work in 10 days, B in 15 days. Together they complete it in:',true,'5 days','6 days','7 days','8 days','B','A rate = 1/10 per day, B rate = 1/15 per day. Combined = 3/30 + 2/30 = 5/30 = 1/6. Time = 6 days.','Easy'),
(2022,'CSAT','Syllogism','Logical Reasoning','CSAT','All cats are dogs. All dogs are animals. Conclusion I: All cats are animals. Conclusion II: All animals are dogs.',true,'Only I follows','Only II follows','Both follow','Neither follows','A','Conclusion I is valid - all cats are animals via the chain. Conclusion II is invalid - not all animals need to be dogs.','Medium'),
(2022,'CSAT','Percentage','Numerical Aptitude','CSAT','A trader marks goods 25% above cost and gives 10% discount. Profit percentage:',true,'10%','12.5%','15%','17.5%','B','CP=100, MP=125, SP=125 times 0.9=112.5. Profit=12.5. So profit percentage = 12.5%.','Medium'),
(2021,'CSAT','Speed Time Distance','Numerical Aptitude','CSAT','A train 150 metres long passes a standing man in 5 seconds. Speed in km/h:',true,'90','100','108','120','C','Speed = 150 divided by 5 = 30 m/s. Convert: 30 times 18 divided by 5 = 108 km/h.','Easy'),
(2020,'CSAT','Reading Comprehension','Comprehension','CSAT','Which best describes the relationship between logic and critical thinking?',true,'They are identical','Logic is subset of critical thinking','Critical thinking is within formal logic','Logic provides structure; critical thinking applies judgment','D','Logic provides formal rules of valid inference. Critical thinking is the broader practical application of analysis and judgment to real-world problems.','Medium')

ON CONFLICT DO NOTHING;

-- ============================================================================
-- 5. DAILY VOCABULARY SEED
-- ============================================================================
INSERT INTO public.daily_vocabulary (word, meaning, upsc_context, example_sentence, category, word_date)
VALUES
('Promissory Estoppel', 'A legal doctrine preventing a party from withdrawing a promise on which another party has relied.', 'Relevant to constitutional law and administrative justice in GS-2.', 'The Supreme Court applied promissory estoppel when the government reneged on industrial licensing promises.', 'Constitutional-Legal', '2026-08-01'),
('Fiscal Federalism', 'The financial relationship between units of government in a federal system including revenue sharing.', 'Central to GS-2 and GS-3 - Finance Commission, GST Council, Centre-State finances.', 'India fiscal federalism underwent significant reform with GST implementation in 2017.', 'Economic-Governance', '2026-08-02'),
('Subsidiarity Principle', 'The principle that decisions should be made at the lowest possible level of governance closest to the people.', 'Relevant to decentralization, Panchayati Raj, and urban governance in GS-2.', 'The 73rd Amendment embodies subsidiarity by devolving powers to gram panchayats.', 'Constitutional-Governance', '2026-08-03'),
('Tragedy of Commons', 'A situation where individuals with access to a public resource act in self-interest, depleting it through collective action.', 'Relevant to GS-3 environment - fisheries, groundwater, climate commons problems.', 'Overgrazing of common pastures and groundwater overextraction exemplify the tragedy of commons in India.', 'Environment-Economic', '2026-08-04'),
('Suzerainty', 'A situation where one state controls the foreign policy of another subordinate state while allowing internal autonomy.', 'Historical: British India relationship with Princely States. IR: great power relations analysis.', 'The British Crown exercised suzerainty over 500 plus princely states through the doctrine of paramountcy.', 'Constitutional-Historical', '2026-08-05'),
('Countervailing Duties', 'Tariffs imposed on imported goods to offset subsidies provided by the exporting country.', 'Relevant to GS-3 international trade, WTO disputes, anti-dumping regulations.', 'India imposed countervailing duties on subsidized Chinese solar panels to protect domestic manufacturers.', 'Economic-International', '2026-08-06'),
('Demographic Dividend', 'The economic growth potential from a large working-age population relative to dependents.', 'India has this window until approximately 2040. Critical for GS-1 social issues and GS-3 economic growth.', 'India must invest in education, health and employment to harness its demographic dividend before it closes.', 'Economic-Social', '2026-08-07'),
('Non-Refoulement', 'The principle under international refugee law forbidding return of refugees to a country where they face persecution.', 'Relevant to GS-2 IR - treatment of Rohingya refugees, international humanitarian law.', 'The principle of non-refoulement under the 1951 Refugee Convention prohibits returning asylum seekers to danger.', 'International Law', '2026-08-08'),
('Comity of Nations', 'The principle of mutual recognition by one nation of the laws and institutions of another.', 'Relevant to GS-2 International Relations - extradition treaties, diplomatic recognition.', 'The fugitive extradition was facilitated by the comity of nations principle between India and UK.', 'International Law', '2026-08-09'),
('Judicial Activism', 'The tendency of judges to interpret the Constitution broadly, creating new rights or overturning legislative acts.', 'Relevant to GS-2 polity - PIL culture, Supreme Court activism, separation of powers debate.', 'The Supreme Court intervention in environmental matters through PILs exemplifies judicial activism in India.', 'Constitutional-Legal', '2026-08-10'),
('Eminent Domain', 'The power of the state to seize private property for public use with just compensation.', 'Relevant to GS-2 land acquisition policies, LARR Act 2013, property rights debates.', 'The LARR Act 2013 reformed India exercise of eminent domain by requiring enhanced compensation and rehabilitation.', 'Constitutional-Legal', '2026-08-11'),
('Cognitive Dissonance', 'The mental discomfort experienced when holding two contradictory beliefs, values, or attitudes simultaneously.', 'Relevant to GS-4 ethics - moral dilemmas, public administration, decision-making under pressure.', 'A civil servant experiences cognitive dissonance when ordered to implement a policy contrary to their ethical beliefs.', 'Ethics-Psychology', '2026-08-12')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- END OF SEED DATA v2
-- ============================================================================
