import { PYQQuestion } from "@/lib/core/types";
import { STATIC_PYQS } from "@/lib/study/pyq-engine";

export type ProductionPYQQuestion = PYQQuestion;

export interface RelationalTest {
  id: string;
  title: string;
  testType: "FULL_MOCK" | "SECTIONAL" | "WEAK_AREA_DRILL" | "CUSTOM";
  subject: string;
  paper: string;
  totalMarks: number;
  durationMinutes: number;
  totalQuestions: number;
  difficulty: "Easy" | "Medium" | "Hard" | "Adaptive";
  isAutoGenerated: boolean;
  questionIds: (number | string)[];
  createdAt: string;
}

export interface RelationalTestQuestion {
  testId: string;
  questionId: number | string;
  orderNumber: number;
  marks: number;
  negativeMarks: number;
  question: ProductionPYQQuestion;
}

/**
 * Question Bank Indexer
 */
export class QuestionBankService {
  private static questions: ProductionPYQQuestion[] = STATIC_PYQS as ProductionPYQQuestion[];

  public static getAllQuestions(): ProductionPYQQuestion[] {
    return this.questions;
  }

  public static filterQuestions(filters: {
    subject?: string;
    topic?: string;
    difficulty?: string;
    year?: number;
    questionType?: string;
  }): ProductionPYQQuestion[] {
    return this.questions.filter((q) => {
      if (filters.subject && filters.subject.toLowerCase() !== "all" && q.subject.toLowerCase() !== filters.subject.toLowerCase()) {
        return false;
      }
      if (filters.topic && filters.topic.toLowerCase() !== "all topics" && q.topic && q.topic.toLowerCase() !== filters.topic.toLowerCase()) {
        return false;
      }
      if (filters.difficulty && filters.difficulty.toLowerCase() !== "all" && q.difficulty && q.difficulty.toLowerCase() !== filters.difficulty.toLowerCase()) {
        return false;
      }
      if (filters.year && q.year !== filters.year) {
        return false;
      }
      if (filters.questionType && (q as any).questionType !== filters.questionType) {
        return false;
      }
      return true;
    });
  }

  /**
   * Assemble a targeted test from question bank without duplicating question data
   */
  public static generateTest(params: {
    title: string;
    testType: "FULL_MOCK" | "SECTIONAL" | "WEAK_AREA_DRILL" | "CUSTOM";
    subject?: string;
    topic?: string;
    questionCount?: number;
    difficulty?: "Easy" | "Medium" | "Hard" | "Adaptive";
  }): { test: RelationalTest; testQuestions: RelationalTestQuestion[] } {
    const matching = this.filterQuestions({
      subject: params.subject,
      topic: params.topic,
      difficulty: params.difficulty === "Adaptive" ? undefined : params.difficulty,
    });

    const count = Math.min(params.questionCount || 25, matching.length > 0 ? matching.length : 10);
    const selected = matching.slice(0, count);

    const testId = `test_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
    const totalMarks = count * 2;
    const durationMinutes = Math.round(count * 1.2); // ~1.2 min per question

    const test: RelationalTest = {
      id: testId,
      title: params.title,
      testType: params.testType,
      subject: params.subject || "Full GS-1 Syllabus",
      paper: "GS-1",
      totalMarks,
      durationMinutes,
      totalQuestions: count,
      difficulty: params.difficulty || "Medium",
      isAutoGenerated: true,
      questionIds: selected.map((q) => q.id),
      createdAt: new Date().toISOString(),
    };

    const testQuestions: RelationalTestQuestion[] = selected.map((q, idx) => ({
      testId,
      questionId: q.id,
      orderNumber: idx + 1,
      marks: 2.0,
      negativeMarks: 0.66,
      question: q,
    }));

    return { test, testQuestions };
  }

  /**
   * Generate a targeted Weak-Area drill test based on identified weak subjects
   */
  public static generateWeakAreaDrill(weakSubject: string, count = 20): { test: RelationalTest; testQuestions: RelationalTestQuestion[] } {
    return this.generateTest({
      title: `Tactical Weakness Diagnostic: ${weakSubject}`,
      testType: "WEAK_AREA_DRILL",
      subject: weakSubject,
      questionCount: count,
      difficulty: "Adaptive",
    });
  }
}
