import { MockTest } from "@/lib/core/types";
import {
  ALL_MOCK_MODULES,
  POLITY_MODULES,
  HISTORY_MODULES,
  ECONOMY_MODULES,
  GEOGRAPHY_MODULES,
  ENVIRONMENT_MODULES,
  SCIENCE_TECH_MODULES,
  CSAT_MOCK_MODULES,
  PRELIMS_YEARLY_MOCK_TESTS,
} from "./subjects";

export const STATIC_MOCK_MODULES: MockTest[] = ALL_MOCK_MODULES;

export {
  POLITY_MODULES,
  HISTORY_MODULES,
  ECONOMY_MODULES,
  GEOGRAPHY_MODULES,
  ENVIRONMENT_MODULES,
  SCIENCE_TECH_MODULES,
  CSAT_MOCK_MODULES,
  PRELIMS_YEARLY_MOCK_TESTS,
};
