/**
 * Universal UPSC CSE Prelims 126-Chapter Canonical Taxonomy
 * Derived from the official UPSC CSE Prelims 30-Year Compendium (WhyNotUPSC)
 * 11 Subjects + Prelims 2025 Special Paper + 126 Chapters
 */

export interface PYQChapter {
  id: string;
  chapterNumber: number;
  name: string;
  pageNumber: number;
  subjectId: string;
  importance?: "High" | "Medium" | "Low";
  pyqFrequency?: number;
  keywords: string[];
}

export interface PYQSubject {
  id: string;
  name: string;
  icon: string;
  color: string;
  startPage: number;
  description: string;
  chapters: PYQChapter[];
}

export const PRELIMS_2025_PAPER: PYQSubject = {
  id: "prelims-2025",
  name: "UPSC CSE Prelims 2025 GS Paper-I",
  icon: "⭐",
  color: "#f59e0b",
  startPage: 1,
  description: "Official Question Paper & Complete Explanations for UPSC CSE Prelims 2025 GS Paper-I",
  chapters: [
    {
      id: "prelims-2025-all",
      chapterNumber: 1,
      name: "UPSC CSE Prelims 2025 GS Paper-I (Complete 100 Questions)",
      pageNumber: 1,
      subjectId: "prelims-2025",
      importance: "High",
      keywords: ["prelims 2025", "2025 paper", "gs paper 1", "latest questions"],
    },
  ],
};

export const PRELIMS_TAXONOMY_SUBJECTS: PYQSubject[] = [
  {
    id: "ancient-history",
    name: "Ancient History",
    icon: "🏛️",
    color: "#eab308",
    startPage: 34,
    description: "From prehistoric sources, Indus Valley, Vedic Era, Mauryan Empire to Gupta & Post-Gupta",
    chapters: [
      {
        id: "ah-1",
        chapterNumber: 1,
        name: "Construction of Ancient History",
        pageNumber: 34,
        subjectId: "ancient-history",
        keywords: ["epigraphy", "numismatics", "archaeology", "inscriptions", "carbon dating", "foreign travellers", "megasthenes", "fa-hien", "hiuen tsang"],
      },
      {
        id: "ah-2",
        chapterNumber: 2,
        name: "Harappan Civilization (Indus Valley)",
        pageNumber: 37,
        subjectId: "ancient-history",
        importance: "High",
        keywords: ["harappa", "mohenjodaro", "dholavira", "lothal", "kalibangan", "bronze age", "seals", "granary", "dockyard", "steatite"],
      },
      {
        id: "ah-3",
        chapterNumber: 3,
        name: "History of the Vedic Period",
        pageNumber: 38,
        subjectId: "ancient-history",
        keywords: ["rig veda", "samaveda", "yajurveda", "atharvaveda", "upanishads", "sabha", "samiti", "ashvamedha", "varnashrama", "vedic culture"],
      },
      {
        id: "ah-4",
        chapterNumber: 4,
        name: "History of Mauryan Age",
        pageNumber: 39,
        subjectId: "ancient-history",
        importance: "High",
        keywords: ["chandragupta", "ashoka", "dhamma", "arthashastra", "kautilya", "rock edicts", "pillar edicts", "megasthenes", "sanchi"],
      },
      {
        id: "ah-5",
        chapterNumber: 5,
        name: "The History of the Gupta Period",
        pageNumber: 44,
        subjectId: "ancient-history",
        importance: "High",
        keywords: ["samudragupta", "chandragupta ii", "vikramaditya", "golden age", "kalidasa", "aryabhata", "navaratnas", "iron pillar", "fa-hien"],
      },
      {
        id: "ah-6",
        chapterNumber: 6,
        name: "Harshavardhan & The Southern Dynasties",
        pageNumber: 46,
        subjectId: "ancient-history",
        importance: "High",
        keywords: ["harsha", "pulakeshin ii", "pallavas", "chalukyas", "cholas", "rashtrakutas", "kannauj", "badami", "aihole inscription", "kanchi"],
      },
      {
        id: "ah-7",
        chapterNumber: 7,
        name: "Art, Literature and Culture During Ancient Times",
        pageNumber: 49,
        subjectId: "ancient-history",
        importance: "High",
        keywords: ["sangam literature", "silappadikaram", "manimekalai", "gandhara art", "mathura art", "amravati", "ajanta", "ellora"],
      },
    ],
  },
  {
    id: "medieval-history",
    name: "Medieval History",
    icon: "⚔️",
    color: "#f97316",
    startPage: 53,
    description: "Delhi Sultanate, Regional Kingdoms, Vijayanagara Empire, Bhakti-Sufi, and Mughal Rule",
    chapters: [
      {
        id: "mh-1",
        chapterNumber: 1,
        name: "Early Medieval Period",
        pageNumber: 53,
        subjectId: "medieval-history",
        keywords: ["tripartite struggle", "gurjara pratiharas", "palas", "rashtrakutas", "feudalism", "rajput clans", "mahmud of ghazni", "muhammad ghori"],
      },
      {
        id: "mh-2",
        chapterNumber: 2,
        name: "The Delhi Sultanate",
        pageNumber: 54,
        subjectId: "medieval-history",
        importance: "High",
        keywords: ["slave dynasty", "khilji", "alauddin khilji", "tughlaq", "muhammad bin tughlaq", "firoz shah tughlaq", "lodhi", "iqta system", "dagh", "chehra"],
      },
      {
        id: "mh-3",
        chapterNumber: 3,
        name: "Regional Kingdoms",
        pageNumber: 59,
        subjectId: "medieval-history",
        keywords: ["bahmani kingdom", "gujarat sultanate", "bengal", "ahom kingdom", "gajapatis", "malwa", "kashmir zain-ul-abidin"],
      },
      {
        id: "mh-4",
        chapterNumber: 4,
        name: "Vijayanagara Empire",
        pageNumber: 61,
        subjectId: "medieval-history",
        importance: "High",
        keywords: ["harihara", "bukka", "krishnadevaraya", "amuktamalyada", "ashtadiggajas", "hampi", "battle of talikota", "nayankara system", "nicolo conti", "abdur razzaq"],
      },
      {
        id: "mh-5",
        chapterNumber: 5,
        name: "Bhakti and Sufi Movement",
        pageNumber: 63,
        subjectId: "medieval-history",
        importance: "High",
        keywords: ["kabir", "guru nanak", "mirabai", "tulsidas", "shankara", "ramanuja", "madhvacharya", "chaitanya", "sufism", "chishti", "suhrawardi", "nizamuddin auliya"],
      },
      {
        id: "mh-6",
        chapterNumber: 6,
        name: "Mughal Period",
        pageNumber: 66,
        subjectId: "medieval-history",
        importance: "High",
        keywords: ["babur", "humayun", "akbar", "jahangir", "shah jahan", "aurangzeb", "mansabdari system", "jagirdari", "sulh-i-kul", "todar mal bandobast", "ain-i-akbari"],
      },
      {
        id: "mh-7",
        chapterNumber: 7,
        name: "Miscellaneous",
        pageNumber: 71,
        subjectId: "medieval-history",
        keywords: ["maratha empire", "shivaji", "ashtapradhan", "chauth", "sardeshmukhi", "medieval terminology", "travellers in medieval india"],
      },
    ],
  },
  {
    id: "modern-history",
    name: "Modern History",
    icon: "📜",
    color: "#ef4444",
    startPage: 76,
    description: "From European Advent, British Expansion, Freedom Struggle (1857–1947), to Independence",
    chapters: [
      {
        id: "mod-1",
        chapterNumber: 1,
        name: "Later Mughals and India at the Beginning of the Modern History",
        pageNumber: 76,
        subjectId: "modern-history",
        keywords: ["bahadur shah i", "farrukhsiyar", "muhammad shah", "nadir shah invasion", "ahmad shah abdali", "carnatic wars"],
      },
      {
        id: "mod-2",
        chapterNumber: 2,
        name: "The Advent of the Europeans in India",
        pageNumber: 77,
        subjectId: "modern-history",
        keywords: ["portuguese", "vasco da gama", "albuquerque", "dutch", "english east india company", "french", "factory settlements"],
      },
      {
        id: "mod-3",
        chapterNumber: 3,
        name: "British Expansion in India",
        pageNumber: 79,
        subjectId: "modern-history",
        importance: "High",
        keywords: ["battle of plassey", "battle of buxar", "subsidiary alliance", "doctrine of lapse", "anglo-mysore wars", "anglo-maratha wars", "tipu sultan"],
      },
      {
        id: "mod-4",
        chapterNumber: 4,
        name: "Peasant and Tribal Movements",
        pageNumber: 82,
        subjectId: "modern-history",
        importance: "High",
        keywords: ["santhal rebellion", "munda rebellion", "birsa munda", "indigo revolt", "deccan riots", "pabna revolt", "kol uprising", "chuar"],
      },
      {
        id: "mod-5",
        chapterNumber: 5,
        name: "Socio-Religious Movements",
        pageNumber: 83,
        subjectId: "modern-history",
        importance: "High",
        keywords: ["raja ram mohan roy", "brahmo samaj", "ishwar chandra vidyasagar", "arya samaj", "dayanand saraswati", "ramakrishna mission", "jyotirao phule", "satyashodhak"],
      },
      {
        id: "mod-6",
        chapterNumber: 6,
        name: "Early Phase National Movement (1885-1905)",
        pageNumber: 85,
        subjectId: "modern-history",
        keywords: ["formation of inc", "moderates", "dadabhai naoroji", "drain of wealth", "gopal krishna gokhale", "pethick lawrence", "w.c. bonnerjee"],
      },
      {
        id: "mod-7",
        chapterNumber: 7,
        name: "Indian National Movement – I (1905-1918)",
        pageNumber: 85,
        subjectId: "modern-history",
        importance: "High",
        keywords: ["swadeshi movement", "partition of bengal", "surat split 1907", "morley-minto reforms", "ghadar party", "home rule league", "tilak", "annie besant", "lucknow pact 1916"],
      },
      {
        id: "mod-8",
        chapterNumber: 8,
        name: "Indian National Movement–II (1918-1929)",
        pageNumber: 90,
        subjectId: "modern-history",
        importance: "High",
        keywords: ["rowlatt act", "jallianwala bagh", "khilafat movement", "non-cooperation movement", "chauri chaura", "swaraj party", "simon commission", "nehru report", "lahore session 1929", "poorna swaraj"],
      },
      {
        id: "mod-9",
        chapterNumber: 9,
        name: "Indian National Movement - III (1930-1947)",
        pageNumber: 96,
        subjectId: "modern-history",
        importance: "High",
        keywords: ["civil disobedience movement", "dandi march", "round table conferences", "gandhi-irwin pact", "poona pact", "quit india movement 1942", "ina", "subhas chandra bose", "cabinet mission", "mountbatten plan"],
      },
      {
        id: "mod-10",
        chapterNumber: 10,
        name: "Governor Generals/Viceroys",
        pageNumber: 109,
        subjectId: "modern-history",
        keywords: ["warren hastings", "cornwallis", "wellesley", "william bentinck", "dalhousie", "canning", "ripon", "curzon", "irwin", "linlithgow"],
      },
      {
        id: "mod-11",
        chapterNumber: 11,
        name: "Constitutional Development",
        pageNumber: 111,
        subjectId: "modern-history",
        importance: "High",
        keywords: ["regulating act 1773", "pitts india act", "charter acts 1813 1833 1853", "government of india act 1858 1909 1919 1935", "dyarchy", "provincial autonomy"],
      },
      {
        id: "mod-12",
        chapterNumber: 12,
        name: "Administrative Changes After 1857",
        pageNumber: 111,
        subjectId: "modern-history",
        keywords: ["queens proclamation 1858", "peel commission", "army reorganization", "police commission", "civil services reforms", "aitchison commission"],
      },
      {
        id: "mod-13",
        chapterNumber: 13,
        name: "Economic Policies of the British",
        pageNumber: 115,
        subjectId: "modern-history",
        keywords: ["zamindari system", "permanent settlement", "ryotwari", "mahalwari", "commercialization of agriculture", "de-industrialization", "railway development"],
      },
      {
        id: "mod-14",
        chapterNumber: 14,
        name: "Development of Education",
        pageNumber: 119,
        subjectId: "modern-history",
        keywords: ["woods despatch 1854", "macaulay minute 1835", "hunter commission", "raleigh commission", "sadler commission", "hartog committee", "wardha scheme"],
      },
      {
        id: "mod-15",
        chapterNumber: 15,
        name: "Prominent Personalities in Modern History",
        pageNumber: 121,
        subjectId: "modern-history",
        keywords: ["mahatma gandhi", "b.r. ambedkar", "jawaharlal nehru", "sardar patel", "bhagat singh", "chandra shekhar azad", "sarojini naidu", "madam cama"],
      },
      {
        id: "mod-16",
        chapterNumber: 16,
        name: "Associations, Journals, Books and Plays",
        pageNumber: 128,
        subjectId: "modern-history",
        importance: "High",
        keywords: ["nil darpan", "anandamath", "young india", "harijan", "kesari", "maratha", "bengal gazette", "hind swaraj", "discovery of india", "poona sarvajanik sabha"],
      },
      {
        id: "mod-17",
        chapterNumber: 17,
        name: "Miscellaneous",
        pageNumber: 131,
        subjectId: "modern-history",
        keywords: ["revolutionary terrorism", "trade union movements", "aituc", "all india kisan sabha", "integration of princely states"],
      },
    ],
  },
  {
    id: "art-and-culture",
    name: "Art and Culture",
    icon: "🏺",
    color: "#a855f7",
    startPage: 134,
    description: "Architecture, Temple Styles, Painting, Music, Classical Dances, Buddhism, Jainism, and Heritage",
    chapters: [
      {
        id: "ac-1",
        chapterNumber: 1,
        name: "Indian Architecture",
        pageNumber: 134,
        importance: "High",
        subjectId: "art-and-culture",
        keywords: ["stupa architecture", "chaitya", "vihara", "rock-cut caves", "indo-islamic architecture", "arches", "domes", "minarets"],
      },
      {
        id: "ac-2",
        chapterNumber: 2,
        name: "Temple Architecture",
        pageNumber: 136,
        importance: "High",
        subjectId: "art-and-culture",
        keywords: ["nagara style", "dravida style", "vesara style", "shikhara", "garbhagriha", "mandapa", "gopuram", "panchayatana", "chola temples", "khajuraho"],
      },
      {
        id: "ac-3",
        chapterNumber: 3,
        name: "Indian Painting",
        pageNumber: 138,
        importance: "High",
        subjectId: "art-and-culture",
        keywords: ["mural paintings", "miniature paintings", "mughal school", "rajput school", "pahari painting", "madhubani", "pattachitra", "kalamkari", "warli"],
      },
      {
        id: "ac-4",
        chapterNumber: 4,
        name: "Indian Music",
        pageNumber: 140,
        subjectId: "art-and-culture",
        keywords: ["hindustani music", "carnatic music", "gharanas", "dhrupad", "khyal", "thumri", "raga", "tala", "trinity of carnatic music", "tyagaraja"],
      },
      {
        id: "ac-5",
        chapterNumber: 5,
        name: "Indian Dance Forms",
        pageNumber: 140,
        subjectId: "art-and-culture",
        importance: "High",
        keywords: ["bharatanatyam", "kathakali", "kathak", "kuchipudi", "odissi", "manipuri", "mohiniyattam", "sattriya", "natya shastra", "abhinaya darpana"],
      },
      {
        id: "ac-6",
        chapterNumber: 6,
        name: "Martial Arts in India",
        pageNumber: 142,
        subjectId: "art-and-culture",
        keywords: ["kalaripayattu", "silambam", "gatka", "thang-ta", "malla-yuddha", "musti yuddha"],
      },
      {
        id: "ac-7",
        chapterNumber: 7,
        name: "Culture in India",
        pageNumber: 142,
        subjectId: "art-and-culture",
        keywords: ["unesco world heritage", "intangible cultural heritage", "fairs and festivals", "kumbh mela", "hornbill", "bihu", "onam", "calendars saka samvat"],
      },
      {
        id: "ac-8",
        chapterNumber: 8,
        name: "Literature",
        pageNumber: 146,
        subjectId: "art-and-culture",
        keywords: ["classical sanskrit literature", "vedic literature", "sangam texts", "persian literature in india", "vernacular poetry", "bhasa", "kalidasa", "banabhatta"],
      },
      {
        id: "ac-9",
        chapterNumber: 9,
        name: "Buddhism and Jainism",
        pageNumber: 148,
        subjectId: "art-and-culture",
        importance: "High",
        keywords: ["gautama buddha", "four noble truths", "eightfold path", "hinayana", "mahayana", "vajrayana", "bodhisattva", "mahavira", "jain tirthankaras", "digambara", "svetambara", "anekantavada", "syadvada"],
      },
      {
        id: "ac-10",
        chapterNumber: 10,
        name: "Science and Technology During Ancient Period",
        pageNumber: 154,
        subjectId: "art-and-culture",
        keywords: ["charaka samhita", "sushruta samhita", "aryabhatiya", "varahamihira", "panini", "brahmagupta", "metallurgy", "zinc smelting zawar"],
      },
      {
        id: "ac-11",
        chapterNumber: 11,
        name: "Sculpture",
        pageNumber: 155,
        subjectId: "art-and-culture",
        keywords: ["dancing girl", "priest king", "ashokan capitals", "lion capital sarnath", "yaksha and yakshini", "didarganj", "natraja bronzes"],
      },
      {
        id: "ac-12",
        chapterNumber: 12,
        name: "Miscellaneous",
        pageNumber: 155,
        subjectId: "art-and-culture",
        keywords: ["traditional puppetry", "handicrafts", "gi tags in crafts", "tribal art forms"],
      },
    ],
  },
  {
    id: "polity",
    name: "Polity",
    icon: "⚖️",
    color: "#3b82f6",
    startPage: 156,
    description: "Constitution, Preamble, Fundamental Rights, DPSP, Parliament, Judiciary, Federalism & Governance",
    chapters: [
      {
        id: "pol-1",
        chapterNumber: 1,
        name: "Historical Background",
        pageNumber: 156,
        subjectId: "polity",
        keywords: ["constituent assembly", "cabinet mission", "objective resolution", "drafting committee", "sources of indian constitution"],
      },
      {
        id: "pol-2",
        chapterNumber: 2,
        name: "Basic Concepts",
        pageNumber: 157,
        subjectId: "polity",
        keywords: ["rule of law", "constitutionalism", "separation of powers", "sovereignty", "republic", "democracy", "basic structure"],
      },
      {
        id: "pol-3",
        chapterNumber: 3,
        name: "Salient Features of the Constitution",
        pageNumber: 159,
        subjectId: "polity",
        keywords: ["written constitution", "rigidity and flexibility", "parliamentary sovereignty vs judicial supremacy", "integrated judicial system", "secular state"],
      },
      {
        id: "pol-4",
        chapterNumber: 4,
        name: "Preamble",
        pageNumber: 162,
        subjectId: "polity",
        importance: "High",
        keywords: ["preamble", "sovereign socialist secular democratic republic", "justice liberty equality fraternity", "berubari union", "kesavananda bharati", "lic of india"],
      },
      {
        id: "pol-5",
        chapterNumber: 5,
        name: "Citizenship",
        pageNumber: 164,
        subjectId: "polity",
        keywords: ["article 5 to 11", "citizenship act 1955", "nri", "pio", "oci", "dual citizenship", "caa", "nrc"],
      },
      {
        id: "pol-6",
        chapterNumber: 6,
        name: "Fundamental Rights",
        pageNumber: 164,
        importance: "High",
        subjectId: "polity",
        keywords: ["article 12 to 35", "part iii", "article 14", "article 19", "article 21", "right to privacy", "article 32", "writs habeas corpus mandamus certiorari prohibition quo warranto"],
      },
      {
        id: "pol-7",
        chapterNumber: 7,
        name: "DPSP",
        pageNumber: 170,
        importance: "High",
        subjectId: "polity",
        keywords: ["directive principles of state policy", "part iv", "article 36 to 51", "socialistic", "gandhian", "liberal-intellectual", "uniform civil code article 44", "article 48a"],
      },
      {
        id: "pol-8",
        chapterNumber: 8,
        name: "Fundamental Duties",
        pageNumber: 174,
        subjectId: "polity",
        keywords: ["part iva", "article 51a", "swaran singh committee", "verma committee", "42nd amendment", "86th amendment"],
      },
      {
        id: "pol-9",
        chapterNumber: 9,
        name: "Constitutional Amendment",
        pageNumber: 175,
        importance: "High",
        subjectId: "polity",
        keywords: ["article 368", "simple majority", "special majority", "ratification by half states", "shankari prasad", "golaknath", "kesavananda bharati", "minerva mills"],
      },
      {
        id: "pol-10",
        chapterNumber: 10,
        name: "Emergency Provisions",
        pageNumber: 179,
        importance: "High",
        subjectId: "polity",
        keywords: ["article 352", "national emergency", "article 356", "presidents rule", "article 360", "financial emergency", "suspension of fundamental rights", "article 358 359"],
      },
      {
        id: "pol-11",
        chapterNumber: 11,
        name: "Funds with Government of India",
        pageNumber: 180,
        subjectId: "polity",
        keywords: ["consolidated fund of india article 266", "public account of india", "contingency fund of india article 267", "charged expenditure"],
      },
      {
        id: "pol-12",
        chapterNumber: 12,
        name: "Systems of Government",
        pageNumber: 181,
        subjectId: "polity",
        keywords: ["parliamentary system", "presidential system", "federal system", "unitary features", "cooperative federalism"],
      },
      {
        id: "pol-13",
        chapterNumber: 13,
        name: "President",
        pageNumber: 183,
        importance: "High",
        subjectId: "polity",
        keywords: ["article 52 to 62", "election of president", "electoral college", "ordinance making power article 123", "pardoning power article 72", "impeachment article 61"],
      },
      {
        id: "pol-14",
        chapterNumber: 14,
        name: "Vice-President",
        pageNumber: 185,
        subjectId: "polity",
        keywords: ["article 63 to 71", "ex-officio chairman of rajya sabha", "election of vice president", "removal of vice president"],
      },
      {
        id: "pol-15",
        chapterNumber: 15,
        name: "Prime Minister",
        pageNumber: 186,
        subjectId: "polity",
        keywords: ["article 74", "article 75", "council of ministers", "collective responsibility", "cabinet", "kitchen cabinet"],
      },
      {
        id: "pol-16",
        chapterNumber: 16,
        name: "Parliament",
        pageNumber: 187,
        importance: "High",
        subjectId: "polity",
        keywords: ["lok sabha", "rajya sabha", "speaker", "sessions of parliament", "adjournment", "prorogation", "dissolution", "money bill article 110", "finance bill", "joint sitting article 108", "parliamentary committees pac estimates puc"],
      },
      {
        id: "pol-17",
        chapterNumber: 17,
        name: "Higher Judiciary: SC and HC",
        pageNumber: 203,
        importance: "High",
        subjectId: "polity",
        keywords: ["supreme court article 124 to 147", "collegium system", "high courts", "original jurisdiction", "appellate jurisdiction", "advisory jurisdiction article 143", "court of record"],
      },
      {
        id: "pol-18",
        chapterNumber: 18,
        name: "Judicial Review",
        pageNumber: 209,
        subjectId: "polity",
        keywords: ["article 13", "judicial review", "judicial activism", "judicial overreach", "pil public interest litigation", "suo motu"],
      },
      {
        id: "pol-19",
        chapterNumber: 19,
        name: "Subordinate Court",
        pageNumber: 209,
        subjectId: "polity",
        keywords: ["district courts", "subordinate judiciary article 233 to 237", "lok adalats", "gram nyayalayas", "tribunals article 323a 323b"],
      },
      {
        id: "pol-20",
        chapterNumber: 20,
        name: "State Legislature",
        pageNumber: 211,
        subjectId: "polity",
        keywords: ["vidhan sabha", "vidhan parishad", "legislative council creation abolition article 169", "state legislature procedures"],
      },
      {
        id: "pol-21",
        chapterNumber: 21,
        name: "Governor",
        pageNumber: 212,
        importance: "High",
        subjectId: "polity",
        keywords: ["article 153 to 167", "appointment of governor", "discretionary powers", "reservation of bills for president article 200 201", "ordinance power article 213"],
      },
      {
        id: "pol-22",
        chapterNumber: 22,
        name: "Centre-State Relations",
        pageNumber: 213,
        importance: "High",
        subjectId: "polity",
        keywords: ["legislative relations", "administrative relations", "financial relations", "union list state list concurrent list", "sarkaria commission", "punchhi commission", "inter-state council article 263"],
      },
      {
        id: "pol-23",
        chapterNumber: 23,
        name: "Local Government: Panchayats and Municipalities",
        pageNumber: 214,
        importance: "High",
        subjectId: "polity",
        keywords: ["73rd constitutional amendment", "74th constitutional amendment", "part ix", "part ixa", "11th schedule", "12th schedule", "pesa act 1996", "state election commission", "state finance commission"],
      },
      {
        id: "pol-24",
        chapterNumber: 24,
        name: "Anti Defection Law",
        pageNumber: 218,
        importance: "High",
        subjectId: "polity",
        keywords: ["10th schedule", "52nd amendment act", "91st amendment act", "disqualification of members", "speakers power", "kihoto hollohan case"],
      },
      {
        id: "pol-25",
        chapterNumber: 25,
        name: "Constitutional Bodies",
        pageNumber: 218,
        importance: "High",
        subjectId: "polity",
        keywords: ["election commission article 324", "upsc spsc article 315 to 323", "finance commission article 280", "cag article 148 to 151", "attorney general article 76", "advocate general article 165", "ncsc ncst ncbc"],
      },
      {
        id: "pol-26",
        chapterNumber: 26,
        name: "Non-Constitutional Bodies",
        pageNumber: 223,
        subjectId: "polity",
        keywords: ["niti aayog", "nhrc", "shrc", "cic", "sic", "cva", "cbi", "lokpal and lokayukta", "competition commission", "national green tribunal ngt"],
      },
      {
        id: "pol-27",
        chapterNumber: 27,
        name: "Governance",
        pageNumber: 224,
        subjectId: "polity",
        keywords: ["good governance", "citizen charter", "rti act 2005", "e-governance", "transparency and accountability", "social audit"],
      },
      {
        id: "pol-28",
        chapterNumber: 28,
        name: "Schedules",
        pageNumber: 224,
        importance: "High",
        subjectId: "polity",
        keywords: ["first schedule to twelfth schedule", "5th schedule", "6th schedule scheduled areas", "7th schedule division of powers", "8th schedule recognized languages"],
      },
      {
        id: "pol-29",
        chapterNumber: 29,
        name: "Miscellaneous",
        pageNumber: 226,
        subjectId: "polity",
        keywords: ["special status article 371", "delimitation commission", "representation of people act 1950 1951", "official language part xvii"],
      },
    ],
  },
  {
    id: "indian-economy",
    name: "Indian Economy",
    icon: "📈",
    color: "#10b981",
    startPage: 237,
    description: "Macroeconomics, Growth, Inflation, Banking, Monetary Policy, Budgeting, Taxation, and External Sector",
    chapters: [
      {
        id: "econ-1",
        chapterNumber: 1,
        name: "Economic Growth",
        pageNumber: 237,
        importance: "High",
        subjectId: "indian-economy",
        keywords: ["gdp", "gnp", "ndp", "nnp", "factor cost", "market price", "nominal gdp", "real gdp", "gdp deflator", "capital output ratio", "potential output"],
      },
      {
        id: "econ-2",
        chapterNumber: 2,
        name: "Planning in India and Economic Reforms",
        pageNumber: 240,
        subjectId: "indian-economy",
        keywords: ["five year plans", "planning commission", "niti aayog", "1991 reforms", "lpg liberalisation privatisation globalisation", "disinvestment"],
      },
      {
        id: "econ-3",
        chapterNumber: 3,
        name: "Agriculture",
        pageNumber: 245,
        importance: "High",
        subjectId: "indian-economy",
        keywords: ["msp minimum support price", "cpc commission for agricultural costs and prices", "pds", "buffer stocks", "food subsidy", "green revolution", "pm kisan", "crop insurance"],
      },
      {
        id: "econ-4",
        chapterNumber: 4,
        name: "Industry",
        pageNumber: 255,
        subjectId: "indian-economy",
        keywords: ["iip index of industrial production", "eight core industries", "make in india", "pli scheme", "msme definition", "disinvestment policy"],
      },
      {
        id: "econ-5",
        chapterNumber: 5,
        name: "Inflation",
        pageNumber: 265,
        importance: "High",
        subjectId: "indian-economy",
        keywords: ["cpi consumer price index", "wpi wholesale price index", "headline inflation", "core inflation", "demand pull", "cost push", "phillips curve", "stagflation"],
      },
      {
        id: "econ-6",
        chapterNumber: 6,
        name: "Money Market",
        pageNumber: 269,
        subjectId: "indian-economy",
        keywords: ["call money", "treasury bills", "commercial paper", "certificate of deposit", "repo rate", "reverse repo", "sdf standing deposit facility", "msf marginal standing facility"],
      },
      {
        id: "econ-7",
        chapterNumber: 7,
        name: "Banking Sector in India",
        pageNumber: 274,
        importance: "High",
        subjectId: "indian-economy",
        keywords: ["rbi monetary policy committee mpc", "crr cash reserve ratio", "slr statutory liquidity ratio", "npa non-performing assets", "ibc insolvency bankruptcy code", "basel norms", "d-sib", "priority sector lending psl"],
      },
      {
        id: "econ-8",
        chapterNumber: 8,
        name: "Taxation",
        pageNumber: 295,
        importance: "High",
        subjectId: "indian-economy",
        keywords: ["direct taxes", "indirect taxes", "gst goods and services tax", "gst council", "tax buoyancy", "tax elasticity", "corporate tax", "laffer curve", "capital gains tax"],
      },
      {
        id: "econ-9",
        chapterNumber: 9,
        name: "Public Finance",
        pageNumber: 299,
        importance: "High",
        subjectId: "indian-economy",
        keywords: ["union budget", "fiscal deficit", "revenue deficit", "primary deficit", "effective revenue deficit", "frbm act", "finance commission", "public debt"],
      },
      {
        id: "econ-10",
        chapterNumber: 10,
        name: "External Sector of India",
        pageNumber: 305,
        importance: "High",
        subjectId: "indian-economy",
        keywords: ["balance of payments bop", "current account deficit cad", "capital account convertibility", "forex reserves", "fdi vs fpi", "exchange rate neer reer", "depreciation vs devaluation", "wto", "imf sdr", "world bank"],
      },
      {
        id: "econ-11",
        chapterNumber: 11,
        name: "Security Market in India",
        pageNumber: 317,
        subjectId: "indian-economy",
        keywords: ["sebi", "stock exchanges bse nse", "primary market ipo", "secondary market", "derivatives", "mutual funds", "reits and invits", "participatory notes p-notes"],
      },
      {
        id: "econ-12",
        chapterNumber: 12,
        name: "Human Development and Sustainable Development",
        pageNumber: 323,
        importance: "High",
        subjectId: "indian-economy",
        keywords: ["hdi human development index", "multidimensional poverty index mpi", "gini coefficient", "lorenz curve", "sdgs sustainable development goals", "demographic dividend"],
      },
      {
        id: "econ-13",
        chapterNumber: 13,
        name: "Important Index and Reports",
        pageNumber: 330,
        subjectId: "indian-economy",
        keywords: ["ease of doing business", "global competitiveness report", "world economic outlook", "human development report", "national multidimensional poverty index niti aayog"],
      },
      {
        id: "econ-14",
        chapterNumber: 14,
        name: "Important Concepts in Economy",
        pageNumber: 331,
        subjectId: "indian-economy",
        keywords: ["liquidity trap", "crowding out effect", "sterilisation by rbi", "cryptocurrency cbdc", "sovereign green bonds"],
      },
    ],
  },
  {
    id: "geography",
    name: "Geography",
    icon: "🌍",
    color: "#06b6d4",
    startPage: 339,
    description: "Physical Geography, Geomorphology, Climatology, Oceanography, Indian Geography, and Map Locations",
    chapters: [
      {
        id: "geo-1",
        chapterNumber: 1,
        name: "Solar System and Evolution of Earth",
        pageNumber: 339,
        subjectId: "geography",
        keywords: ["big bang theory", "interior of earth", "crust mantle core", "seismic waves p and s waves", "shadow zones", "earths magnetic field", "latitudes and longitudes", "time zones"],
      },
      {
        id: "geo-2",
        chapterNumber: 2,
        name: "Climatology",
        pageNumber: 342,
        importance: "High",
        subjectId: "geography",
        keywords: ["structure of atmosphere", "troposphere stratosphere", "insolation and heat budget", "pressure belts", "coriolis force", "planetary winds trade winds westerlies", "monsoon el nino la nina iod", "cyclones tropical extra-tropical", "types of clouds", "koppen climate classification"],
      },
      {
        id: "geo-3",
        chapterNumber: 3,
        name: "Oceanography",
        pageNumber: 356,
        importance: "High",
        subjectId: "geography",
        keywords: ["ocean bottom relief continental shelf slope trenches", "ocean currents warm and cold currents", "tides spring and neap", "salinity and temperature distribution", "coral reefs atolls fringing barrier"],
      },
      {
        id: "geo-4",
        chapterNumber: 4,
        name: "Geomorphology",
        pageNumber: 361,
        importance: "High",
        subjectId: "geography",
        keywords: ["continental drift theory", "plate tectonics", "sea floor spreading", "earthquakes and volcanoes", "weathering and mass wasting", "fluvial landforms", "aeolian landforms", "karst topography", "glacial landforms"],
      },
      {
        id: "geo-5",
        chapterNumber: 5,
        name: "Human and Economic Geography",
        pageNumber: 365,
        subjectId: "geography",
        keywords: ["population distribution density", "migration push and pull factors", "urbanisation", "location of industries webers theory", "mineral belts iron coal petroleum", "transport and trade routes"],
      },
      {
        id: "geo-6",
        chapterNumber: 6,
        name: "Agriculture",
        pageNumber: 386,
        importance: "High",
        subjectId: "geography",
        keywords: ["cropping patterns rabi kharif zaid", "rice wheat cotton sugarcane tea coffee conditions", "irrigation methods drip sprinkler canal", "soil types alluvium black red laterite arid saline"],
      },
      {
        id: "geo-7",
        chapterNumber: 7,
        name: "Indian Geography",
        pageNumber: 390,
        importance: "High",
        subjectId: "geography",
        keywords: ["himalayas northern plains peninsular plateau", "drainage systems himalayan vs peninsular rivers", "ganga brahmaputra indus godavari krishna kaveri narmada tapi", "climate of india monsoon mechanism", "natural vegetation and forests of india"],
      },
      {
        id: "geo-8",
        chapterNumber: 8,
        name: "Location/Map Based : Indian Geography",
        pageNumber: 419,
        importance: "High",
        subjectId: "geography",
        keywords: ["mountain peaks passes zoji la rohtang nathu la", "hills western ghats eastern ghats nilgiri cardamom", "islands andaman nicobar lakshadweep ten degree channel", "straits gulf of mannar palk strait", "wetlands lakes chilika wular loktak sambhar pulicat"],
      },
      {
        id: "geo-9",
        chapterNumber: 9,
        name: "Location/Map Based : World Geography",
        pageNumber: 444,
        importance: "High",
        subjectId: "geography",
        keywords: ["world seas red sea black sea caspian sea mediterranean baltic", "straits malacca hormuz bab-el-mandeb gibraltar bosphorus", "rivers nile amazon danube mekong", "mountain ranges andes rockies alps urals atlas", "deserts sahara atacama gobi kalahari"],
      },
      {
        id: "geo-10",
        chapterNumber: 10,
        name: "Miscellaneous",
        pageNumber: 467,
        subjectId: "geography",
        keywords: ["international boundaries radcliffe macmahon durand", "gis and remote sensing in geography"],
      },
    ],
  },
  {
    id: "environment-and-ecology",
    name: "Environment and Ecology",
    icon: "🌱",
    color: "#22c55e",
    startPage: 470,
    description: "Ecosystems, Biodiversity, Pollution, Climate Change, Ramsar, IUCN, Protected Areas, and Wildlife",
    chapters: [
      {
        id: "env-1",
        chapterNumber: 1,
        name: "Ecology, Ecosystem and Functions of Ecosystem",
        pageNumber: 470,
        importance: "High",
        subjectId: "environment-and-ecology",
        keywords: ["ecological succession", "food chain food web trophic levels", "ecological pyramids number biomass energy", "biogeochemical cycles carbon nitrogen phosphorus", "ecotone and edge effect", "ecological niche"],
      },
      {
        id: "env-2",
        chapterNumber: 2,
        name: "Biodiversity",
        pageNumber: 475,
        importance: "High",
        subjectId: "environment-and-ecology",
        keywords: ["genetic species ecosystem diversity", "alpha beta gamma diversity", "biodiversity hotspots criteria in india", "threats to biodiversity evil quartet", "invasive alien species", "ex-situ vs in-situ conservation"],
      },
      {
        id: "env-3",
        chapterNumber: 3,
        name: "Agriculture and Environment",
        pageNumber: 480,
        importance: "High",
        subjectId: "environment-and-ecology",
        keywords: ["zero budget natural farming zbnf", "organic farming", "biochar", "conservation agriculture zero tillage", "methane emissions from paddy livestock", "stubble burning", "integrated pest management"],
      },
      {
        id: "env-4",
        chapterNumber: 4,
        name: "Pollution",
        pageNumber: 485,
        importance: "High",
        subjectId: "environment-and-ecology",
        keywords: ["air pollution pm2.5 pm10 aqi smog acid rain", "water pollution bod cod eutrophication bioaccumulation biomagnification", "plastic pollution single-use microplastics", "e-waste rules hazardous waste", "noise and radioactive pollution"],
      },
      {
        id: "env-5",
        chapterNumber: 5,
        name: "Climate Change",
        pageNumber: 494,
        importance: "High",
        subjectId: "environment-and-ecology",
        keywords: ["greenhouse effect ghg gases gwp global warming potential", "ocean acidification", "sea level rise", "carbon footprint carbon credits carbon sequestration", "ipcc reports", "ndcs nationally determined contributions"],
      },
      {
        id: "env-6",
        chapterNumber: 6,
        name: "Environmental Laws, Conventions and Policies",
        pageNumber: 499,
        importance: "High",
        subjectId: "environment-and-ecology",
        keywords: ["wildlife protection act 1972 schedules", "environment protection act 1986", "biological diversity act 2002", "forest rights act 2006", "unfccc kyoto paris cop", "cbd cartagena nagoya", "ramsar convention wetlands", "cites stockholm basel rotterdam"],
      },
      {
        id: "env-7",
        chapterNumber: 7,
        name: "Environmental Organisations",
        pageNumber: 510,
        importance: "High",
        subjectId: "environment-and-ecology",
        keywords: ["unep", "iucn red list criteria", "wwf world wide fund", "global environment facility gef", "green climate fund gcf", "national biodiversity authority nba", "cpcb central pollution control board", "animal welfare board"],
      },
      {
        id: "env-8",
        chapterNumber: 8,
        name: "Protected Areas for the Biodiversity Conservation",
        pageNumber: 513,
        importance: "High",
        subjectId: "environment-and-ecology",
        keywords: ["national parks", "wildlife sanctuaries", "biosphere reserves core buffer transition man and biosphere mab", "tiger reserves project tiger ntca", "elephant reserves project elephant elephant corridors", "community reserves conservation reserves"],
      },
      {
        id: "env-9",
        chapterNumber: 9,
        name: "Species",
        pageNumber: 518,
        importance: "High",
        subjectId: "environment-and-ecology",
        keywords: ["critically endangered species", "tiger lion cheetah elephant rhino dugong gharial gangetic dolphin great indian bustard olive ridley hangul red panda", "keystone species flagship species umbrella species indicator species"],
      },
      {
        id: "env-10",
        chapterNumber: 10,
        name: "Miscellaneous",
        pageNumber: 527,
        subjectId: "environment-and-ecology",
        keywords: ["renewable energy solar wind green hydrogen", "circular economy", "environment impact assessment eia", "coastal regulation zone crz rules"],
      },
    ],
  },
  {
    id: "science-and-technology",
    name: "Science and Technology",
    icon: "🔬",
    color: "#6366f1",
    startPage: 530,
    description: "Biotechnology, Space Missions, Defense, IT, Quantum Computing, Nano, Physics, Chemistry, and Biology",
    chapters: [
      {
        id: "scitech-1",
        chapterNumber: 1,
        name: "Biotechnology",
        pageNumber: 530,
        importance: "High",
        subjectId: "science-and-technology",
        keywords: ["dna rna recombinant dna technology", "crispr-cas9 gene editing", "gm crops bt cotton bt brinjal dmh-11", "cloning stem cells", "monoclonal antibodies", "three-parent baby mitochondrial replacement"],
      },
      {
        id: "scitech-2",
        chapterNumber: 2,
        name: "Health",
        pageNumber: 538,
        importance: "High",
        subjectId: "science-and-technology",
        keywords: ["vaccines mrna dna vector subunit", "antibiotic resistance amr", "malnutrition wasting stunting", "who initiatives universal health coverage", "ayushman bharat"],
      },
      {
        id: "scitech-3",
        chapterNumber: 3,
        name: "Diseases",
        pageNumber: 541,
        importance: "High",
        subjectId: "science-and-technology",
        keywords: ["infectious diseases viral bacterial fungal parasitic", "tb tuberculosis drug resistant", "malaria dengue chikungunya nipah ebola covid-19 zika", "non-communicable diseases diabetes cancer cardiovascular", "zoonotic diseases"],
      },
      {
        id: "scitech-4",
        chapterNumber: 4,
        name: "Information and Communication Technology",
        pageNumber: 544,
        importance: "High",
        subjectId: "science-and-technology",
        keywords: ["artificial intelligence ai machine learning deep learning", "blockchain distributed ledger technology web3", "quantum computing qubits quantum key distribution", "5g 6g optical fibre internet of things iot", "cybersecurity malware ransomware phishing zero-day", "supercomputers param series"],
      },
      {
        id: "scitech-5",
        chapterNumber: 5,
        name: "Nanoscience and Nanotechnology",
        pageNumber: 553,
        subjectId: "science-and-technology",
        keywords: ["nanomaterials carbon nanotubes graphene fullerenes", "applications of nanotechnology in medicine drug delivery agriculture energy", "nanotoxicity"],
      },
      {
        id: "scitech-6",
        chapterNumber: 6,
        name: "Space And Space Technology",
        pageNumber: 555,
        importance: "High",
        subjectId: "science-and-technology",
        keywords: ["isro launch vehicles pslv gslv sslv lvm3", "orbits leo geo sso lagrange points l1 l2", "chandrayaan gaganyaan aditya-l1 mangalyaan shukrayaan", "navic irnss gps", "space telescopes james webb hubble astrosat", "gravitational waves ligo"],
      },
      {
        id: "scitech-7",
        chapterNumber: 7,
        name: "Defence Technology",
        pageNumber: 563,
        subjectId: "science-and-technology",
        keywords: ["missiles ballistic vs cruise agni prithvi brahmos akash nag", "aircraft carriers ins vikrant ins vikramaditya", "submarines scorpene ins arihant nuclear triad", "fighter jets tejas rafale", "uavs drones anti-drone systems"],
      },
      {
        id: "scitech-8",
        chapterNumber: 8,
        name: "Nuclear Technology",
        pageNumber: 565,
        subjectId: "science-and-technology",
        keywords: ["nuclear fission vs fusion", "three stage nuclear power programme india thorium based", "pressurized heavy water reactor phwr fast breeder reactor fbr", "iaea safeguards npt nsog"],
      },
      {
        id: "scitech-9",
        chapterNumber: 9,
        name: "Miscellaneous",
        pageNumber: 566,
        subjectId: "science-and-technology",
        keywords: ["emerging technologies li-ion vs sodium-ion batteries", "green hydrogen fuel cells electrolysers", "particle physics cern higgs boson neutrino observatory"],
      },
      {
        id: "scitech-10",
        chapterNumber: 10,
        name: "Physics",
        pageNumber: 583,
        subjectId: "science-and-technology",
        keywords: ["optics total internal reflection dispersion", "electromagnetic spectrum radio to gamma", "gravitation satellites escape velocity", "sound and ultrasound applications", "thermodynamics and heat transfer"],
      },
      {
        id: "scitech-11",
        chapterNumber: 11,
        name: "Chemistry",
        pageNumber: 599,
        subjectId: "science-and-technology",
        keywords: ["acids bases and ph indicators", "polymers plastics biodegradable plastics", "metals and non-metals alloys corrosion", "organic compounds hydrocarbons", "chemistry in daily life soaps detergents fertilizers"],
      },
      {
        id: "scitech-12",
        chapterNumber: 12,
        name: "Biology",
        pageNumber: 612,
        subjectId: "science-and-technology",
        keywords: ["cell structure organelles mitochondria ribosome", "plant physiology photosynthesis transpiration xylem phloem", "human digestive respiratory circulatory nervous systems", "genetics mendelian genetics inheritance chromosomes"],
      },
    ],
  },
  {
    id: "international-relations",
    name: "International Relations and Current Affairs",
    icon: "🌐",
    color: "#8b5cf6",
    startPage: 641,
    description: "Multilateral Treaties, Geopolitics, Regional Blocs, UN Bodies, and Global Summits",
    chapters: [
      {
        id: "ir-1",
        chapterNumber: 1,
        name: "International Relations",
        pageNumber: 641,
        importance: "High",
        subjectId: "international-relations",
        keywords: ["un unsc general assembly icj", "brics sco g20 g7 asean quad aukus", "wto imf world bank bii", "indias neighbourhood policy act east look west", "maritime security indo-pacific choke points"],
      },
      {
        id: "ir-2",
        chapterNumber: 2,
        name: "Current Affairs",
        pageNumber: 660,
        importance: "High",
        subjectId: "international-relations",
        keywords: ["major international summits", "geopolitical conflicts regions in news middle east red sea south china sea", "global treaties bilateral pacts"],
      },
      {
        id: "ir-3",
        chapterNumber: 3,
        name: "Miscellaneous",
        pageNumber: 670,
        subjectId: "international-relations",
        keywords: ["international tribunals", "refugee conventions unhcr", "disarmament treaties npt ctbt chemical weapons convention"],
      },
    ],
  },
  {
    id: "general-knowledge",
    name: "General Knowledge (1995-2010)",
    icon: "📚",
    color: "#64748b",
    startPage: 680,
    description: "Vintage UPSC CSE Prelims General Studies Questions (1995–2010 Archival Collection)",
    chapters: [
      {
        id: "gk-1",
        chapterNumber: 1,
        name: "General Awareness : World",
        pageNumber: 680,
        subjectId: "general-knowledge",
        keywords: ["world leaders capitals currencies treaties international days vintage questions"],
      },
      {
        id: "gk-2",
        chapterNumber: 2,
        name: "Contemporary Events : World",
        pageNumber: 698,
        subjectId: "general-knowledge",
        keywords: ["historical world events 1995 2000 2005 2010 global developments"],
      },
      {
        id: "gk-3",
        chapterNumber: 3,
        name: "General Awareness : India",
        pageNumber: 711,
        subjectId: "general-knowledge",
        keywords: ["indian institutions first in india awards bharat ratna padma national symbols"],
      },
      {
        id: "gk-4",
        chapterNumber: 4,
        name: "Contemporary Events : India",
        pageNumber: 739,
        subjectId: "general-knowledge",
        keywords: ["india developments 1995 to 2010 vintage government schemes commissions"],
      },
      {
        id: "gk-5",
        chapterNumber: 5,
        name: "Sports And Games",
        pageNumber: 758,
        subjectId: "general-knowledge",
        keywords: ["olympics asian games commonwealth cricket world cup tennis grand slams sports terminology"],
      },
    ],
  },
];

// Helper to get all subjects including the special Prelims 2025 paper
export const ALL_TAXONOMY_SUBJECTS: PYQSubject[] = [
  PRELIMS_2025_PAPER,
  ...PRELIMS_TAXONOMY_SUBJECTS,
];

// Map lookup helpers
const subjectMap = new Map<string, PYQSubject>();
const chapterMap = new Map<string, PYQChapter>();

ALL_TAXONOMY_SUBJECTS.forEach((subj) => {
  subjectMap.set(subj.id.toLowerCase(), subj);
  subjectMap.set(subj.name.toLowerCase(), subj);
  subj.chapters.forEach((ch) => {
    chapterMap.set(ch.id.toLowerCase(), ch);
    chapterMap.set(`${subj.id}:${ch.name.toLowerCase()}`, ch);
  });
});

export function getSubjectByIdOrName(query: string): PYQSubject | undefined {
  if (!query) return undefined;
  return subjectMap.get(query.trim().toLowerCase());
}

export function getAllChaptersForSubject(subjectIdOrName: string): PYQChapter[] {
  const subj = getSubjectByIdOrName(subjectIdOrName);
  return subj ? subj.chapters : [];
}

export function findChapterById(chapterId: string): PYQChapter | undefined {
  return chapterMap.get(chapterId.toLowerCase());
}

/**
 * Intelligent topic auto-classifier: Given a question text and explanation,
 * computes keyword scoring to suggest the best matching subject and chapter
 */
export function autoClassifyQuestion(
  questionText: string,
  explanationText: string = ""
): { subject: PYQSubject; chapter: PYQChapter; confidence: number } | null {
  const combined = `${questionText} ${explanationText}`.toLowerCase();

  let bestSubject: PYQSubject | null = null;
  let bestChapter: PYQChapter | null = null;
  let highestScore = 0;

  for (const subject of PRELIMS_TAXONOMY_SUBJECTS) {
    for (const chapter of subject.chapters) {
      let score = 0;
      for (const kw of chapter.keywords) {
        if (combined.includes(kw.toLowerCase())) {
          score += 3;
        }
      }
      // Also match chapter name words
      const chapterWords = chapter.name.toLowerCase().split(/\s+/);
      for (const word of chapterWords) {
        if (word.length > 4 && combined.includes(word)) {
          score += 1;
        }
      }

      if (score > highestScore) {
        highestScore = score;
        bestSubject = subject;
        bestChapter = chapter;
      }
    }
  }

  if (bestSubject && bestChapter && highestScore >= 3) {
    return {
      subject: bestSubject,
      chapter: bestChapter,
      confidence: Math.min(100, highestScore * 10),
    };
  }

  return null;
}
