"use client";

import React, { useState, useEffect } from "react";
import AppUniversalHeader from "@/components/AppUniversalHeader";
import AuthGuard from "@/components/auth/AuthGuard";
import { sound } from "@/lib/audio/sound-engine";
import { formatDate } from "@/lib/core/utils";
import Link from "next/link";

interface NotificationItem {
  id: string;
  type: "REVISION" | "STREAK" | "TELEGRAM" | "MISSION" | "SYSTEM";
  title: string;
  message: string;
  createdAt: string;
  actionRoute?: string;
  actionLabel?: string;
  read: boolean;
}

export default function NotificationsPage() {
  const [notifications, setNotifications] = useState<NotificationItem[]>([
    {
      id: "notif-1",
      type: "REVISION",
      title: "🔄 Spaced Active Recall Due",
      message: "You have 3 high-yield topics due today in your SM-2 queue: Fundamental Rights, Money Bills, and RBI Monetary Policy.",
      createdAt: new Date().toISOString(),
      actionRoute: "/revision",
      actionLabel: "Start Flashcards",
      read: false,
    },
    {
      id: "notif-2",
      type: "MISSION",
      title: "⚡ Daily Mission Ready",
      message: "Your personalized mission for today has been generated by the WhyNotUPSC Brain: 5 tasks totaling ~3.5 hours.",
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      actionRoute: "/dashboard",
      actionLabel: "View Mission",
      read: false,
    },
    {
      id: "notif-3",
      type: "STREAK",
      title: "🔥 Study Streak Maintained",
      message: "Congratulations! You have completed a 4-day study streak. Keep the focus momentum alive today.",
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      actionRoute: "/study-plan",
      actionLabel: "Study Sprints",
      read: true,
    },
    {
      id: "notif-4",
      type: "TELEGRAM",
      title: "📡 Live Commander Alert",
      message: "Daily UPSC Editorial Compilation and GS-2 Dimensions published in Current Affairs hub.",
      createdAt: new Date(Date.now() - 172800000).toISOString(),
      actionRoute: "/current-affairs",
      actionLabel: "Read Editorials",
      read: true,
    },
  ]);

  const handleMarkAllRead = () => {
    sound.playSelect();
    setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
  };

  const handleDismiss = (id: string) => {
    sound.playHover();
    setNotifications((prev) => prev.filter((n) => n.id !== id));
  };

  return (
    <AuthGuard>
      <main className="min-h-screen bg-[#040406] text-[#F5F5F5] font-sans selection:bg-[#D8A63A] selection:text-black">
        <AppUniversalHeader moduleName="Cadet Notification Center" moduleBadge="ALERTS & DISPATCHES" />

        <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6 space-y-8">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/10 pb-4">
            <div>
              <p className="font-mono text-[11px] font-black uppercase tracking-[0.25em] text-[#F4C95D]">
                TELEMETRY & DIRECTIVES
              </p>
              <h1 className="text-2xl sm:text-3xl font-black text-white mt-1">
                Cadet Notification Hub
              </h1>
              <p className="text-xs text-[#8C8C8C] mt-1 font-sans">
                Review spaced repetition alerts, mission directives, telegram dispatches, and streak milestones.
              </p>
            </div>

            <button
              onClick={handleMarkAllRead}
              className="rounded-2xl border border-white/10 bg-white/5 hover:bg-white/10 px-4 py-2 font-mono text-xs text-white/70 hover:text-white transition shrink-0"
            >
              Mark All as Read ✓
            </button>
          </div>

          <div className="space-y-4">
            {notifications.length === 0 ? (
              <div className="rounded-3xl border border-dashed border-white/10 p-12 text-center text-xs text-white/40">
                All notifications cleared. You are completely up to date with your UPSC preparation schedule!
              </div>
            ) : (
              notifications.map((n) => (
                <div
                  key={n.id}
                  className={`rounded-3xl border p-5 sm:p-6 transition flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${
                    !n.read
                      ? "border-[#D8A63A]/40 bg-gradient-to-r from-[#1c1404] to-[#0d0d0d] shadow-[0_0_20px_rgba(216,166,58,0.1)]"
                      : "border-white/5 bg-[#0d0d0d] text-white/60"
                  }`}
                >
                  <div className="space-y-1.5 max-w-2xl">
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-sm text-white">{n.title}</span>
                      {!n.read && (
                        <span className="rounded-full bg-[#D8A63A] px-2 py-0.2 font-mono text-[9px] font-black text-black">
                          NEW
                        </span>
                      )}
                      <span className="font-mono text-[10px] text-white/40">· {formatDate(n.createdAt)}</span>
                    </div>
                    <p className="text-xs text-white/80 leading-relaxed font-sans">{n.message}</p>
                  </div>

                  <div className="flex items-center gap-2 shrink-0 self-end sm:self-center">
                    {n.actionRoute && (
                      <Link
                        href={n.actionRoute}
                        onClick={() => sound.playWarp()}
                        className="rounded-xl bg-[#D8A63A] hover:bg-[#F4C95D] px-4 py-2 font-mono text-xs font-bold text-black transition"
                      >
                        {n.actionLabel || "Open →"}
                      </Link>
                    )}
                    <button
                      onClick={() => handleDismiss(n.id)}
                      className="rounded-xl border border-white/10 bg-white/5 hover:bg-white/10 px-3 py-2 font-mono text-xs text-white/40 hover:text-white transition"
                    >
                      Dismiss ✕
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </main>
    </AuthGuard>
  );
}
