import { NextRequest, NextResponse } from "next/server";
import { getDailyCurrentAffairs } from "@/lib/current-affairs/cache";
import { ApiResponse, WeeklyReportSummary } from "@/lib/core/types";

/**
 * Generates a clean, formatted 1-page Sunday PDF / Text Document
 */
function generateCondensedDigestText(summary: WeeklyReportSummary, starredNotes: any[] = [], missedFlashcards: any[] = []): string {
  const radar = summary.radarMetrics || {
    gs1Hours: 6.5,
    gs2Hours: 8.0,
    gs3Hours: 7.5,
    gs4Hours: 5.0,
    csatHours: 4.5,
    essayHours: 3.5,
    targetHoursPerPaper: 7.0,
    prelimsEliminationAccuracy: 78,
    mainsAnswerSpeedWpm: 18.5,
    avgMainsTimePer150W: 7.8,
    avgMainsTimePer250W: 11.5,
  };

  let doc = `========================================================================\n`;
  doc += `     WHYNOTUPSC — OFFICIAL SUNDAY CADET PERFORMANCE & REVISION DIGEST    \n`;
  doc += `========================================================================\n\n`;
  doc += `REPORT PERIOD: ${summary.startDate || "Current Week"} to ${summary.endDate || "Today"}\n`;
  doc += `CONSISTENCY SCORE: ${summary.consistencyScore || 0} / 100\n`;
  doc += `STUDY HOURS: ${summary.totalCompletedHours || 0}h Logged / ${summary.weeklyTargetHours || 42}h Target (${summary.hoursCompletionRate || 0}% Completion)\n\n`;
  doc += `------------------------------------------------------------------------\n`;
  doc += `1. 6-AXIS GS PAPER RADAR DISTRIBUTION (Target: ${radar.targetHoursPerPaper}h/paper)\n`;
  doc += `------------------------------------------------------------------------\n`;
  doc += `• GS-1 (History, Geography, Indian Society)      : ${radar.gs1Hours} Hours\n`;
  doc += `• GS-2 (Polity, Constitution, Governance, IR)    : ${radar.gs2Hours} Hours\n`;
  doc += `• GS-3 (Economy, Agriculture, Science, Security) : ${radar.gs3Hours} Hours\n`;
  doc += `• GS-4 (Ethics, Integrity & Case Studies)        : ${radar.gs4Hours} Hours\n`;
  doc += `• CSAT (Quantitative Aptitude & Logic)           : ${radar.csatHours} Hours\n`;
  doc += `• ESSAY (Cross-Disciplinary Synthesis)           : ${radar.essayHours} Hours\n\n`;
  doc += `------------------------------------------------------------------------\n`;
  doc += `2. TACTICAL VELOCITY & ACCURACY METRICS\n`;
  doc += `------------------------------------------------------------------------\n`;
  doc += `• Prelims 50/50 Elimination Success Rate        : ${radar.prelimsEliminationAccuracy}%\n`;
  doc += `• Mains Answer Writing Velocity                 : ${radar.mainsAnswerSpeedWpm} Words / Minute\n`;
  doc += `• Benchmark Speed per 10-Marker (150 Words)     : ~${radar.avgMainsTimePer150W} Minutes\n`;
  doc += `• Benchmark Speed per 15-Marker (250 Words)     : ~${radar.avgMainsTimePer250W} Minutes\n\n`;

  if (starredNotes.length > 0) {
    doc += `------------------------------------------------------------------------\n`;
    doc += `3. TOP STARRED HIGH-YIELD REVISION NOTES\n`;
    doc += `------------------------------------------------------------------------\n`;
    starredNotes.slice(0, 5).forEach((n: any, idx: number) => {
      doc += `${idx + 1}. ${n.title || "Key Synthesis"} [${(n.tags || []).join(", ")}]\n`;
    });
    doc += `\n`;
  }

  if (missedFlashcards.length > 0) {
    doc += `------------------------------------------------------------------------\n`;
    doc += `4. ACTIVE RECALL PRIORITY (MISSED FLASHCARDS)\n`;
    doc += `------------------------------------------------------------------------\n`;
    missedFlashcards.slice(0, 5).forEach((fc: any, idx: number) => {
      doc += `${idx + 1}. ${fc.front || "Concept Recall"}\n`;
    });
    doc += `\n`;
  }

  if (summary.aiMentorReview?.executiveSummary) {
    doc += `------------------------------------------------------------------------\n`;
    doc += `5. AI STRATEGIC MENTOR DIRECTIVE\n`;
    doc += `------------------------------------------------------------------------\n`;
    doc += `"${summary.aiMentorReview.executiveSummary}"\n\n`;
  }

  doc += `========================================================================\n`;
  doc += `      GENERATED BY REDROOM OS COMMAND MATRIX • ALL RIGHTS RESERVED      \n`;
  doc += `========================================================================\n`;

  return doc;
}

/**
 * Sends a PDF/Text Document to Telegram via sendDocument
 */
async function sendTelegramDocument(
  token: string,
  chatId: string | number,
  fileContent: string,
  fileName: string,
  caption: string
): Promise<boolean> {
  try {
    const formData = new FormData();
    formData.append("chat_id", String(chatId));
    formData.append("caption", caption);
    formData.append("parse_mode", "Markdown");

    const blob = new Blob([fileContent], { type: "application/pdf" });
    formData.append("document", blob, fileName);

    const res = await fetch(`https://api.telegram.org/bot${token}/sendDocument`, {
      method: "POST",
      body: formData,
    });

    const json = await res.json().catch(() => ({}));
    return Boolean(json.ok);
  } catch {
    return false;
  }
}

/**
 * Core Dispatch Execution Engine
 */
async function executeDispatch(params: {
  type: string;
  chatId?: string | number;
  title?: string;
  message?: string;
  priority?: string;
  weeklySummary?: any;
  starredNotes?: any[];
  missedFlashcards?: any[];
  sendPdf?: boolean;
}) {
  const token = process.env.TELEGRAM_BOT_TOKEN;
  const targetChatId = params.chatId || process.env.TELEGRAM_CHAT_ID;

  let dispatchText = "";
  let documentContent: string | null = null;
  let documentFileName = "Sunday_Cadet_Revision_Digest.pdf";

  // 1. ADMIN OR OUTBOX SYNC TELEMETRY ALERT
  if (params.title || params.message || params.type === "admin_alert" || params.type === "alert") {
    const alertTitle = params.title || "⚠️ REDROOM CADET ALERT";
    const alertMsg = params.message || "System notification triggered.";
    const alertPri = params.priority || "NORMAL";

    dispatchText = `🚨 *${alertTitle}*\n`;
    dispatchText += `⚡ *Priority:* ${alertPri}\n`;
    dispatchText += `🕒 *Timestamp:* ${new Date().toLocaleString("en-IN")}\n\n`;
    dispatchText += `${alertMsg}\n\n`;
    dispatchText += `_REDROOM OS Telemetry Dispatcher_`;
  }
  // 2. WEEKLY PERFORMANCE AUDIT & CONDENSED REVISION DIGEST
  else if (params.type === "weekly_audit") {
    const summary = params.weeklySummary || {
      startDate: "Monday",
      endDate: "Sunday",
      consistencyScore: 88,
      totalCompletedHours: 38.5,
      weeklyTargetHours: 42,
      hoursCompletionRate: 91,
      weeklyNotesSummary: params.starredNotes || [],
      radarMetrics: {
        gs1Hours: 6.5,
        gs2Hours: 8.0,
        gs3Hours: 7.5,
        gs4Hours: 5.0,
        csatHours: 4.5,
        essayHours: 3.5,
        targetHoursPerPaper: 7.0,
        prelimsEliminationAccuracy: 78,
        mainsAnswerSpeedWpm: 18.5,
        avgMainsTimePer150W: 7.8,
        avgMainsTimePer250W: 11.5,
      },
    };

    const radar = summary.radarMetrics;

    dispatchText = `📊 *WHYNOTUPSC SUNDAY CADET AUDIT & 1-PAGE REVISION DIGEST*\n`;
    dispatchText += `🗓️ *Week Span:* ${summary.startDate || "Current Week"} to ${summary.endDate || "Today"}\n`;
    dispatchText += `⚡ *Consistency Score:* ${summary.consistencyScore || 0}/100 | *Logged Hours:* ${summary.totalCompletedHours || 0}h / ${summary.weeklyTargetHours || 42}h (${summary.hoursCompletionRate || 0}%)\n\n`;

    dispatchText += `🕸️ *GS RADAR ALLOCATION (Target: ${radar.targetHoursPerPaper}h/paper):*\n`;
    dispatchText += `• *GS-1 (History/Geo/Society):* ${radar.gs1Hours}h\n`;
    dispatchText += `• *GS-2 (Polity/Gov/IR):* ${radar.gs2Hours}h\n`;
    dispatchText += `• *GS-3 (Economy/Env/Sci/Sec):* ${radar.gs3Hours}h\n`;
    dispatchText += `• *GS-4 (Ethics & Case Studies):* ${radar.gs4Hours}h\n`;
    dispatchText += `• *CSAT (Quant/Logic/RC):* ${radar.csatHours}h\n`;
    dispatchText += `• *Essay (Synthesis):* ${radar.essayHours}h\n\n`;

    dispatchText += `🎯 *TACTICAL VELOCITY METRICS:*\n`;
    dispatchText += `• *Prelims 50/50 Elimination Accuracy:* ${radar.prelimsEliminationAccuracy}%\n`;
    dispatchText += `• *Mains Writing Velocity:* ${radar.mainsAnswerSpeedWpm} WPM (~${radar.avgMainsTimePer150W}m for 10M, ~${radar.avgMainsTimePer250W}m for 15M)\n\n`;

    if ((params.starredNotes || []).length > 0) {
      dispatchText += `⭐ *WEEK'S HIGH-YIELD STARRED REVISION NOTES:*\n`;
      params.starredNotes!.slice(0, 3).forEach((n: any, idx: number) => {
        dispatchText += `${idx + 1}. *${n.title || "Key Synthesis"}* (${(n.tags || []).join(", ")})\n`;
      });
      dispatchText += `\n`;
    }

    if ((params.missedFlashcards || []).length > 0) {
      dispatchText += `🔁 *ACTIVE RECALL PRIORITY (Missed Flashcards):*\n`;
      params.missedFlashcards!.slice(0, 3).forEach((fc: any, idx: number) => {
        dispatchText += `${idx + 1}. ${fc.front || "Concept Recall"}\n`;
      });
      dispatchText += `\n`;
    }

    dispatchText += `📄 _Attached: 1-Page Printable Sunday Revision Digest PDF_\n`;
    dispatchText += `🚀 _Generated by REDROOM OS Tactical Command_`;

    documentContent = generateCondensedDigestText(summary, params.starredNotes, params.missedFlashcards);
  }
  // 3. DAILY CURRENT AFFAIRS BRIEF (DEFAULT)
  else {
    const articles = await getDailyCurrentAffairs();
    const topArticles = articles.slice(0, 4);

    dispatchText = `🏛️ *WHYNOTUPSC DAILY INTELLIGENCE BRIEF (07:00 AM IST)*\n📅 Date: ${new Date().toLocaleDateString("en-IN")}\n\n`;

    topArticles.forEach((art, i) => {
      dispatchText += `*${i + 1}. [${art.gsPaper}] ${art.title}*\n`;
      dispatchText += `📰 _Source: ${art.source}_\n`;
      dispatchText += `${art.summary.slice(0, 160)}...\n`;
      if (art.prelimsPoints && art.prelimsPoints.length > 0) {
        dispatchText += `🎯 *Prelims Eliminator:* ${art.prelimsPoints[0]}\n`;
      }
      dispatchText += `\n`;
    });

    dispatchText += `🚀 _Prepared by WHYNOTUPSC AI Operating System_`;
  }

  // Clamping for Telegram text
  if (dispatchText.length > 4000) {
    dispatchText = dispatchText.slice(0, 3950) + "\n\n_...[Report truncated]_";
  }

  // Deliver to Telegram if Token & Chat ID configured
  if (token && targetChatId) {
    // If document content exists, send file attachment
    if (documentContent) {
      await sendTelegramDocument(
        token,
        targetChatId,
        documentContent,
        documentFileName,
        "📄 Official WHYNOTUPSC Sunday 1-Page Revision Digest & Audit PDF"
      );
    }

    // Send Message Text
    await fetch(`https://api.telegram.org/bot${token}/sendMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chat_id: targetChatId,
        text: dispatchText,
        parse_mode: "Markdown",
        disable_web_page_preview: true,
      }),
    });
  }

  return {
    message: token && targetChatId ? "Dispatched successfully to Telegram." : "Generated digest successfully.",
    formattedText: dispatchText,
  };
}

/**
 * GET Handler for Vercel Cron Invocations (07:00 AM IST)
 */
export async function GET(request: NextRequest): Promise<NextResponse<ApiResponse<any>>> {
  try {
    const { searchParams } = new URL(request.url);
    const type = searchParams.get("type") || "daily_brief";

    const result = await executeDispatch({ type });
    return NextResponse.json({ success: true, data: result });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "Cron dispatch exception";
    return NextResponse.json(
      { success: false, error: { code: "CRON_DISPATCH_FAILED", message: msg } },
      { status: 500 }
    );
  }
}

/**
 * POST Handler for Manual Client or Telemetry Dispatches
 */
export async function POST(
  request: NextRequest
): Promise<NextResponse<ApiResponse<{ message: string; formattedText?: string }>>> {
  try {
    const body = await request.json().catch(() => ({}));
    const result = await executeDispatch(body);
    return NextResponse.json({ success: true, data: result });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "Telegram broadcast exception";
    return NextResponse.json(
      {
        success: false,
        error: {
          code: "DISPATCH_FAILED",
          message: msg,
        },
      },
      { status: 500 }
    );
  }
}
