"use client";

import { useState } from "react";
import { sound } from "@/lib/audio/sound-engine";

interface DAFQuestion {
  member: string;
  question: string;
  intent: string;
  recommendedFramework: string;
}

export default function DAFProfilerModal() {
  const [homeDistrict, setHomeDistrict] = useState("Varanasi, Uttar Pradesh");
  const [graduation, setGraduation] = useState("Computer Science & Engineering");
  const [hobby, setHobby] = useState("Vipassana Meditation & Marathon Running");
  const [questions, setQuestions] = useState<DAFQuestion[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerateQuestions = () => {
    setIsGenerating(true);
    sound.playWarp();

    setTimeout(() => {
      setQuestions([
        {
          member: "Board Chairman (IAS Retd.)",
          question: `You are from ${homeDistrict}. The district has witnessed heavy cultural tourism and infrastructure transformation. How do you balance heritage conservation with modern urban carrying capacity?`,
          intent: "Tests local administrative awareness, urban planning, and sustainable tourism balance.",
          recommendedFramework: "1. Acknowledge economic multiplier of tourism. 2. Highlight carrying capacity studies (2nd ARC). 3. Propose decentralized satellite transit and zoning regulations.",
        },
        {
          member: "Member 1 (Technical & Governance Specialist)",
          question: `With a degree in ${graduation}, why do you want to leave the private tech sector to enter the generalist civil services where technical skills might be underutilized?`,
          intent: "Tests motivation, public service ethos, and ability to leverage tech in digital governance.",
          recommendedFramework: "1. Clarify that modern civil services require techno-administrative leadership (e-governance, DPI, AI in public delivery). 2. Civil services offer pan-India social impact at population scale.",
        },
        {
          member: "Member 2 (Psychology & Public Administration)",
          question: `You listed '${hobby}' as your hobby. How does this practice prepare you for the high-stress, emotionally volatile environment of a District Magistrate during law and order crises?`,
          intent: "Evaluates emotional intelligence (EQ), equanimity under pressure, and genuine pursuit of the hobby.",
          recommendedFramework: "1. Vipassana cultivates 'Sthitaprajna' (equanimity) and objective observation without immediate impulsive reaction. 2. Marathons teach grit, pacing, and resilience during long administrative crises.",
        },
      ]);
      setIsGenerating(false);
      sound.playVictory();
    }, 600);
  };

  return (
    <div className="rounded-3xl border border-white/10 bg-[#0d0d0d] p-6 shadow-2xl backdrop-blur-xl font-sans">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-white/10 pb-5 gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="flex h-2 w-2 rounded-full bg-pink-400 animate-pulse" />
            <span className="font-mono text-[10px] font-black uppercase tracking-widest text-pink-400">
              DAF-II INTELLIGENCE PROFILER // UPSC PERSONALITY TEST
            </span>
          </div>
          <h3 className="mt-1 font-mono text-base font-bold text-white">
            Custom DAF Cross-Examination Generator
          </h3>
          <p className="text-xs text-[#8C8C8C]">
            Simulate targeted questions generated by the 5-member interview board based on your home state, graduation, and hobbies.
          </p>
        </div>
      </div>

      {/* Inputs Form */}
      <div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-3 font-mono text-xs">
        <div>
          <label className="text-[#8C8C8C] block mb-1">📍 Home District & State:</label>
          <input
            type="text"
            value={homeDistrict}
            onChange={(e) => setHomeDistrict(e.target.value)}
            className="w-full rounded-xl border border-white/10 bg-black/60 px-3 py-2 text-white focus:border-[#D8A63A] focus:outline-none"
          />
        </div>
        <div>
          <label className="text-[#8C8C8C] block mb-1">🎓 Graduation Background:</label>
          <input
            type="text"
            value={graduation}
            onChange={(e) => setGraduation(e.target.value)}
            className="w-full rounded-xl border border-white/10 bg-black/60 px-3 py-2 text-white focus:border-[#D8A63A] focus:outline-none"
          />
        </div>
        <div>
          <label className="text-[#8C8C8C] block mb-1">🏃 Extracurriculars & Hobbies:</label>
          <input
            type="text"
            value={hobby}
            onChange={(e) => setHobby(e.target.value)}
            className="w-full rounded-xl border border-white/10 bg-black/60 px-3 py-2 text-white focus:border-[#D8A63A] focus:outline-none"
          />
        </div>
      </div>

      <div className="mt-4 flex justify-end">
        <button
          onClick={handleGenerateQuestions}
          disabled={isGenerating}
          className="rounded-xl border border-pink-500/40 bg-gradient-to-r from-purple-600 to-pink-600 px-5 py-2 font-mono text-xs font-bold text-white shadow-lg hover:opacity-90 transition"
        >
          {isGenerating ? "Analyzing DAF Matrix..." : "🎯 Generate Board Cross-Examination"}
        </button>
      </div>

      {/* Questions Render List */}
      {questions.length > 0 && (
        <div className="mt-6 space-y-4">
          <h4 className="font-mono text-xs font-bold uppercase tracking-wider text-[#F4C95D]">
            Simulated UPSC Interview Board Interrogations ({questions.length})
          </h4>
          {questions.map((q, idx) => (
            <div
              key={idx}
              className="rounded-2xl border border-white/10 bg-black/40 p-5 font-sans space-y-2 transition hover:border-pink-500/40"
            >
              <div className="flex items-center justify-between border-b border-white/5 pb-2">
                <span className="font-mono text-xs font-bold text-pink-300">
                  🏛️ {q.member}
                </span>
                <span className="font-mono text-[10px] text-[#8C8C8C]">
                  Question {idx + 1}
                </span>
              </div>
              <p className="text-sm font-semibold text-white/95 leading-relaxed">
                "{q.question}"
              </p>
              <div className="text-[11px] text-white/60">
                <strong className="text-amber-200">Board's Intent:</strong> {q.intent}
              </div>
              <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-3 text-xs text-white/80">
                <strong className="text-emerald-400 block font-mono mb-1">
                  💡 Model Articulation Blueprint:
                </strong>
                {q.recommendedFramework}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
