import { ChillGame, GameAchievement } from "../types";

export const CHILL_GAMES: ChillGame[] = [
  {
    id: "game_react",
    slug: "react",
    name: "WHY NOT REACT?",
    code: "ARCADE-01",
    tagline: "Precision Reaction Calibration",
    description: "A glowing target appears after a random delay. Click the instant the signal changes. False starts result in an immediate penalty.",
    icon: "⚡",
    durationLabel: "20–30s",
    scoringType: "ASCENDING_TIME",
    unit: "ms",
    bestScoreFormat: (score: number) => (score > 0 ? `${score} ms` : "No Record"),
    rules: [
      "Wait for the red standby aura to turn electric gold.",
      "Click or tap immediately upon color transition.",
      "Clicks before the signal trigger 'TOO EARLY' disqualification for that round.",
      "Average reaction time over 5 valid attempts determines your final score.",
    ],
    tips: [
      "Keep your finger lightly resting on the screen or mouse.",
      "Breathe steadily and focus on peripheral color changes.",
    ],
    achievements: ["Lightning Reflex (<200ms)", "Sub-250 Club", "Flawless Reaction Streak"],
  },
  {
    id: "game_memory_vault",
    slug: "memory-vault",
    name: "MEMORY VAULT",
    code: "ARCADE-02",
    tagline: "Cognitive Pattern Recall",
    description: "Flip cards and uncover identical pairs. Test visual memory, spatial orientation, and pattern retention across 4 difficulty tiers.",
    icon: "🧠",
    durationLabel: "1–3 min",
    scoringType: "DESCENDING_POINTS",
    unit: "pts",
    bestScoreFormat: (score: number) => (score > 0 ? `${score.toLocaleString()} pts` : "No Record"),
    rules: [
      "Tap any card to reveal its symbol or UPSC concept.",
      "Find the matching card in the minimum number of moves.",
      "Faster completion and higher accuracy multiply your final score.",
    ],
    tips: [
      "Map card positions in 2x2 quadrants mentally.",
      "Prioritize clearing corner cards first.",
    ],
    achievements: ["Vault Master", "Perfect Recall (0 Misses)", "Extreme Speed Clear"],
  },
  {
    id: "game_focus_flow",
    slug: "focus-flow",
    name: "FOCUS FLOW",
    code: "ARCADE-03",
    tagline: "Endless Kinetic Avoidance",
    description: "Pilot an energy orb through an infinite obsidian slipstream. Dodge cosmic barriers, collect gold nodes, and maintain flow state.",
    icon: "🌌",
    durationLabel: "Endless",
    scoringType: "DESCENDING_POINTS",
    unit: "pts",
    bestScoreFormat: (score: number) => (score > 0 ? `${score.toLocaleString()} pts` : "No Record"),
    rules: [
      "Use mouse, touch, or arrow keys to maneuver the golden core.",
      "Dodge red obstacles and collect glowing golden energy rings.",
      "Velocity and obstacle density ramp up every 15 seconds.",
    ],
    tips: [
      "Keep your orb in the central third of the screen to react faster.",
      "Prioritize survival over high-risk energy collections.",
    ],
    achievements: ["Deep Flow (10k pts)", "Orb Whisperer (60s+)", "Energy Magnet (50 Nodes)"],
  },
  {
    id: "game_quick_duel",
    slug: "quick-duel",
    name: "QUICK DUEL",
    code: "ARCADE-04",
    tagline: "Real-Time 1v1 Reaction Clash",
    description: "Challenge another UPSC aspirant to a live reaction face-off. Quick Match or generate a custom room code for direct duels.",
    icon: "⚔️",
    durationLabel: "15s / Round",
    scoringType: "ASCENDING_TIME",
    unit: "ms",
    bestScoreFormat: (score: number) => (score > 0 ? `${score} ms` : "No Record"),
    rules: [
      "Both players ready up in the room.",
      "A random countdown initiates. First to click after GO! wins the round.",
      "Clicking early triggers an automatic round forfeit (TOO EARLY).",
      "Best of 3 rounds claims victory.",
    ],
    tips: [
      "Do not anticipate the pulse; react solely to the visual GO cue.",
      "Use a stable network connection for low latency.",
    ],
    achievements: ["Duel Champion", "Undefeated 5-Streak", "Instant Draw Master"],
  },
  {
    id: "game_word_rush",
    slug: "word-rush",
    name: "WORD RUSH",
    code: "ARCADE-05",
    tagline: "High-Speed Anagram Matrix",
    description: "Unscramble high-yield terms across Geography, History, Polity, and General knowledge before the 15-second timer expires.",
    icon: "🔤",
    durationLabel: "60s Sprint",
    scoringType: "DESCENDING_POINTS",
    unit: "pts",
    bestScoreFormat: (score: number) => (score > 0 ? `${score.toLocaleString()} pts` : "No Record"),
    rules: [
      "Type or tap letter tiles to unscramble the presented word.",
      "Each solved word awards base points plus remaining time bonus.",
      "Maintain consecutive streaks for up to 3x score multipliers.",
    ],
    tips: [
      "Look for common prefixes and suffixes first.",
      "Filter words by the active category hint on screen.",
    ],
    achievements: ["Lexicon Titan", "10-Word Sprint", "UPSC Vocabulary Master"],
  },
  {
    id: "game_blink",
    slug: "blink",
    name: "BLINK",
    code: "ARCADE-06",
    tagline: "Progressive Attention & Sequence",
    description: "Memorize and reproduce progressive sequences of light and sound. Speed and pattern complexity increase with each round.",
    icon: "👁️",
    durationLabel: "Cognitive",
    scoringType: "HIGHEST_STREAK",
    unit: "streak",
    bestScoreFormat: (score: number) => (score > 0 ? `${score} Streak` : "No Record"),
    rules: [
      "Watch the sequence of glowing nodes light up.",
      "Repeat the sequence in the exact order.",
      "A single mistake ends the session.",
      "Score is equal to the highest completed sequence length.",
    ],
    tips: [
      "Assign numbers 1–4 to the quadrants and memorize numeric strings.",
      "Maintain rhythmic breathing between sequences.",
    ],
    achievements: ["15-Sequence Master", "Subconscious Echo", "Flawless Memory"],
  },
];

export const CHILL_ACHIEVEMENTS: GameAchievement[] = [
  {
    id: "first_break",
    name: "FIRST RESET",
    description: "Completed your first Chill Zone break session.",
    icon: "☕",
  },
  {
    id: "quick_hands",
    name: "QUICK HANDS",
    description: "Achieved a sub-220ms reaction time in Why Not React?",
    icon: "⚡",
    gameSlug: "react",
  },
  {
    id: "memory_master",
    name: "VAULT CRACKER",
    description: "Cleared Hard or Extreme Memory Vault with >90% accuracy.",
    icon: "🧠",
    gameSlug: "memory-vault",
  },
  {
    id: "flow_survivor",
    name: "FLOW ADEPTER",
    description: "Scored over 5,000 points in Focus Flow.",
    icon: "🌌",
    gameSlug: "focus-flow",
  },
  {
    id: "duel_winner",
    name: "DUEL CONQUEROR",
    description: "Won a 1v1 Quick Duel against another aspirant.",
    icon: "⚔️",
    gameSlug: "quick-duel",
  },
  {
    id: "word_master",
    name: "WORD SPRINT",
    description: "Unscrambled 8+ words in a single Word Rush round.",
    icon: "🔤",
    gameSlug: "word-rush",
  },
  {
    id: "blink_titan",
    name: "ATTENTION TITAN",
    description: "Achieved a streak of 12+ in Blink.",
    icon: "👁️",
    gameSlug: "blink",
  },
  {
    id: "mind_master",
    name: "BALANCE ACHIEVED",
    description: "Played all 6 Chill Zone games and returned to studying.",
    icon: "👑",
    gameSlug: "global",
  },
];
